package com.github.aborg0.builders.example.simple

import builders.configuration.GenerateBuilder
import builders.configuration.BuilderStyle

@GenerateBuilder(style = BuilderStyle.Simple)
final case class Simple private(field1: String, field2: Int, field3: Boolean)

object Simple {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Simple
  private val modeTag: String = "simple"
  private val builderApi: Any = builder
  private type Builder = (field1: Field1Input => AfterStep1)
  inline def builder: Builder = (field1= (field1: Field1Input) => step1(field1))
  private type Field1Input = String
  private type Field2Input = Int
  private type Field3Input = Boolean
  private type AfterStep1 = (field2: Field2Input => AfterStep2)
  private type AfterStep2 = (field3: Field3Input => AfterStep3)
  private type AfterStep3 = Simple
  private inline def step1(field1: Field1Input): AfterStep1 = (field2= (field2: Field2Input) => step2(field1, field2))
  private inline def step2(field1: Field1Input, field2: Field2Input): AfterStep2 = (field3= (field3: Field3Input) => step3(field1, field2, field3))
  private inline def step3(field1: Field1Input, field2: Field2Input, field3: Field3Input): AfterStep3 = Simple(field1, field2, field3)
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}



object Example {
  def main(args: Array[String]): Unit = {
    val instance = Simple.builder.field1("hello").field2(42).field3(true)
    println(instance)
    val region = Region("US") match {
      case Right(value) => value
      case Left(error) => throw new IllegalArgumentException(error)
    }
    val date = AcceptableDate("2024-01-01") match {
      case Right(value) => value
      case Left(error) => throw new IllegalArgumentException(error)
    }
    val various = Various.builder.simple(instance)
    .gender(Gender.Female)
    .region(region)
    .tags(List("tag1", "tag2"))
    .date(date)
    println(various)
  }
}
