package com.github.aborg0.builders.example.simple

import builders.configuration.GenerateBuilder
import builders.configuration.BuilderStyle

@GenerateBuilder(style = BuilderStyle.Simple)
final case class Various private(simple: Simple, gender: Gender, region: Region, tags: List[String], date: AcceptableDate)

object Various {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Simple
  private val modeTag: String = "simple"
  private val builderApi: Any = builder
  private type Builder = (simple: SimpleInput => AfterStep1)
  inline def builder: Builder = (simple= (simple: SimpleInput) => step1(simple))
  private type SimpleInput = Simple
  private type GenderInput = Gender
  private type RegionInput = Region
  private type TagsInput = List[String]
  private type DateInput = AcceptableDate
  private type AfterStep1 = (gender: GenderInput => AfterStep2)
  private type AfterStep2 = (region: RegionInput => AfterStep3)
  private type AfterStep3 = (tags: TagsInput => AfterStep4)
  private type AfterStep4 = (date: DateInput => AfterStep5)
  private type AfterStep5 = Various
  private inline def step1(simple: SimpleInput): AfterStep1 = (gender= (gender: GenderInput) => step2(simple, gender))
  private inline def step2(simple: SimpleInput, gender: GenderInput): AfterStep2 = (region= (region: RegionInput) => step3(simple, gender, region))
  private inline def step3(simple: SimpleInput, gender: GenderInput, region: RegionInput): AfterStep3 = (tags= (tags: TagsInput) => step4(simple, gender, region, tags))
  private inline def step4(simple: SimpleInput, gender: GenderInput, region: RegionInput, tags: TagsInput): AfterStep4 = (date= (date: DateInput) => step5(simple, gender, region, tags, date))
  private inline def step5(simple: SimpleInput, gender: GenderInput, region: RegionInput, tags: TagsInput, date: DateInput): AfterStep5 = Various(simple, gender, region, tags, date)
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}

