import builders.configuration.*

@GenerateBuilder(style = BuilderStyle.Simple)
case class SimpleUser(i: Int, name: String)

object SimpleUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Simple
  private val modeTag: String = "simple"
  private val builderApi: Any = builder
  private type Builder = (i: IInput => AfterStep1)
  inline def builder: Builder = (i= (i: IInput) => step1(i))
  private type IInput = Int
  private type NameInput = String
  private type AfterStep1 = (name: NameInput => AfterStep2)
  private type AfterStep2 = SimpleUser
  private inline def step1(i: IInput): AfterStep1 = (name= (name: NameInput) => step2(i, name))
  private inline def step2(i: IInput, name: NameInput): AfterStep2 = SimpleUser(i, name)
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}
