package com.github.aborg0.builders.example.validating

import builders.configuration.GenerateBuilder
import builders.configuration.BuilderStyle
import com.github.aborg0.builders.example.simple.Simple
import com.github.aborg0.builders.example.simple.Gender
import com.github.aborg0.builders.example.simple.AcceptableDate
import com.github.aborg0.builders.example.simple.Region

@GenerateBuilder(style = BuilderStyle.Validating)
final case class VariousValid private(simple: Simple, gender: Gender, region: Region, tags: List[String], date: AcceptableDate)

object VariousValid {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Validating
  private val modeTag: String = "validating"
  private val builderApi: Any = builder
    type Builder = (simple: SimpleInput => AfterStep1)
  def builder: Builder = builderState0()
  def builderAllow: Builder = builderState0()
  def builderNoAllow: Builder = builderState0()
  private type SimpleInput = Simple
  private type GenderInput = Gender
  private type RegionInput = String
  private type TagsInput = List[String]
  private type DateInput = String
  private type AfterStep1 = (gender: GenderInput => AfterStep2)
  private type AfterStep2 = (region: RegionInput => AfterStep3)
  private type AfterStep3 = (tags: TagsInput => AfterStep4)
  private type AfterStep4 = (date: DateInput => AfterStep5)
  private type AfterStep5 = zio.prelude.ZValidation[Nothing, Any, VariousValid]
  private type SimpleValidation = zio.prelude.ZValidation[Nothing, Nothing, Simple]
  private inline def validateSimple(simpleValue: SimpleInput): SimpleValidation =
    zio.prelude.ZValidation.succeed(simpleValue)
  private type GenderValidation = zio.prelude.ZValidation[Nothing, Nothing, Gender]
  private inline def validateGender(genderValue: GenderInput): GenderValidation =
    zio.prelude.ZValidation.succeed(genderValue)
  private type RegionValidation = zio.prelude.ZValidation[Nothing, Any, Region]
  private inline def validateRegion(regionValue: RegionInput): RegionValidation =
    zio.prelude.ZValidation.fromEither(Region(regionValue)).mapError(error => error: Any)
  private type TagsValidation = zio.prelude.ZValidation[Nothing, Nothing, List[String]]
  private inline def validateTags(tagsValue: TagsInput): TagsValidation =
    zio.prelude.ZValidation.succeed(tagsValue)
  private type DateValidation = zio.prelude.ZValidation[Nothing, Any, AcceptableDate]
  private inline def validateDate(dateValue: DateInput): DateValidation =
    zio.prelude.ZValidation.fromEither(AcceptableDate(dateValue)).mapError(error => error: Any)
  private inline def builderState0(): Builder =
    (simple = (simpleValue: SimpleInput) => builderState1(simpleValue))
  private inline def builderState1(simpleValue: SimpleInput): AfterStep1 =
    (gender = (genderValue: GenderInput) => builderState2(simpleValue, genderValue))
  private inline def builderState2(simpleValue: SimpleInput, genderValue: GenderInput): AfterStep2 =
    (region = (regionValue: RegionInput) => builderState3(simpleValue, genderValue, regionValue))
  private inline def builderState3(simpleValue: SimpleInput, genderValue: GenderInput, regionValue: RegionInput): AfterStep3 =
    (tags = (tagsValue: TagsInput) => builderState4(simpleValue, genderValue, regionValue, tagsValue))
  private inline def builderState4(simpleValue: SimpleInput, genderValue: GenderInput, regionValue: RegionInput, tagsValue: TagsInput): AfterStep4 =
    (date = (dateValue: DateInput) => buildValidationFromValues(simpleValue, genderValue, regionValue, tagsValue, dateValue))
  private inline def builderState5(simpleValue: SimpleInput, genderValue: GenderInput, regionValue: RegionInput, tagsValue: TagsInput, dateValue: DateInput): AfterStep5 = buildValidationFromValues(simpleValue, genderValue, regionValue, tagsValue, dateValue)
  private def buildValidationFromValues(simpleValue: SimpleInput, genderValue: GenderInput, regionValue: RegionInput, tagsValue: TagsInput, dateValue: DateInput): zio.prelude.ZValidation[Nothing, Any, VariousValid] =
    zio.prelude.Validation.validateWith(
      validateSimple(simpleValue),
      validateGender(genderValue),
      validateRegion(regionValue),
      validateTags(tagsValue),
      validateDate(dateValue)
    )((simpleValidated, genderValidated, regionValidated, tagsValidated, dateValidated) => VariousValid(simpleValidated, genderValidated, regionValidated, tagsValidated, dateValidated))
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  private val smartConstructorMode: builders.configuration.SmartConstructorMode = builders.configuration.SmartConstructorMode.ZValidation
  private val combineErrors: builders.configuration.ErrorCombination = builders.configuration.ErrorCombination.Union
  private val generatedCodeShape: builders.configuration.GeneratedCodeShape = builders.configuration.GeneratedCodeShape.Readable
  // format: on
}

