import builders.configuration.*

@GenerateBuilder(
  style = BuilderStyle.Validating,
  pathMode = PathMode.FullCollectionAware,
  primitivePolicy = PrimitivePolicy.PrimitiveAndWrappedIfDerivable
)
case class ValidatingUser(id: Int, code: String)

object ValidatingUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Validating
  private val modeTag: String = "validating"
  private val builderApi: Any = builder
    type Builder = (id: IdInput => AfterStep1)
  def builder: Builder = builderState0()
  def builderAllow: Builder = builderState0()
  def builderNoAllow: Builder = builderState0()
  private type IdInput = Int
  private type CodeInput = String
  private type AfterStep1 = (code: CodeInput => AfterStep2)
  private type AfterStep2 = zio.prelude.ZValidation[Nothing, Nothing, ValidatingUser]
  private type IdValidation = zio.prelude.ZValidation[Nothing, Nothing, Int]
  private inline def validateId(idValue: IdInput): IdValidation =
    zio.prelude.ZValidation.succeed(idValue)
  private type CodeValidation = zio.prelude.ZValidation[Nothing, Nothing, String]
  private inline def validateCode(codeValue: CodeInput): CodeValidation =
    zio.prelude.ZValidation.succeed(codeValue)
  private inline def builderState0(): Builder =
    (id = (idValue: IdInput) => builderState1(idValue))
  private inline def builderState1(idValue: IdInput): AfterStep1 =
    (code = (codeValue: CodeInput) => buildValidationFromValues(idValue, codeValue))
  private inline def builderState2(idValue: IdInput, codeValue: CodeInput): AfterStep2 = buildValidationFromValues(idValue, codeValue)
  private def buildValidationFromValues(idValue: IdInput, codeValue: CodeInput): zio.prelude.ZValidation[Nothing, Nothing, ValidatingUser] =
    zio.prelude.Validation.validateWith(
      validateId(idValue),
      validateCode(codeValue)
    )((idValidated, codeValidated) => ValidatingUser(idValidated, codeValidated))
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  private val smartConstructorMode: builders.configuration.SmartConstructorMode = builders.configuration.SmartConstructorMode.ZValidation
  private val combineErrors: builders.configuration.ErrorCombination = builders.configuration.ErrorCombination.Union
  private val generatedCodeShape: builders.configuration.GeneratedCodeShape = builders.configuration.GeneratedCodeShape.Readable
  // format: on
}