import builders.configuration.*

@GenerateBuilder(
  style = BuilderStyle.Validating,
  pathMode = PathMode.FullCollectionAware,
  primitivePolicy = PrimitivePolicy.PrimitiveAndWrappedIfDerivable
)
case class ValidatingUser(id: Int, code: String)

object ValidatingUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Validating
  private val modeTag: String = "validating"
  private val builderApi: Any = builder
  private class ValidatedBuilderSelectable[T, E, R <: scala.NamedTuple.AnyNamedTuple](
  private val underlying: Tuple1[Any => Any]
) extends Selectable {
  type Fields = BuilderFields[R, T, E]
  def selectDynamic(name: String): Any = underlying._1
}
private type BuilderFields[R <: scala.NamedTuple.AnyNamedTuple, T, E] <: scala.NamedTuple.AnyNamedTuple =
  scala.NamedTuple.DropNames[R] match {
    case Tuple1[h] =>
      scala.NamedTuple[scala.NamedTuple.Names[R], Tuple1[h => zio.prelude.ZValidation[Nothing, E, T]]]
    case h *: t =>
      scala.NamedTuple[
        Tuple1[Tuple.Head[scala.NamedTuple.Names[R]]],
        Tuple1[h => ValidatedBuilderSelectable[T, E, scala.NamedTuple[Tuple.Tail[scala.NamedTuple.Names[R]], t]]]
      ]
  }
  private type Builder = ValidatedBuilderSelectable[ValidatingUser, ?, (id: Int, code: String)]
  def builder: Builder = builderState0()
  def builderAllow: Builder = builderState0()
  def builderNoAllow: Builder = builderState0()
  private type IdInput = Int
  private type CodeInput = String
  private type AfterStep1 = ValidatedBuilderSelectable[ValidatingUser, ?, (code: CodeInput)]
  private type AfterStep2 = zio.prelude.ZValidation[Nothing, ?, ValidatingUser]
  private type IdValidation = zio.prelude.ZValidation[Nothing, ?, Int]
  private inline given idSmartConstructor: (IdInput => IdValidation) =
    (idValue: IdInput) => zio.prelude.ZValidation.succeed(idValue).asInstanceOf[IdValidation]
  private inline def validateId(idValue: IdInput): IdValidation =
    summon[IdInput => IdValidation].apply(idValue)
  private type CodeValidation = zio.prelude.ZValidation[Nothing, ?, String]
  private inline given codeSmartConstructor: (CodeInput => CodeValidation) =
    (codeValue: CodeInput) => zio.prelude.ZValidation.succeed(codeValue).asInstanceOf[CodeValidation]
  private inline def validateCode(codeValue: CodeInput): CodeValidation =
    summon[CodeInput => CodeValidation].apply(codeValue)
  private inline def builderState0(): Builder =
    new ValidatedBuilderSelectable[ValidatingUser, Any, (id: Int, code: String)](
      Tuple1((idValue: IdInput) => builderState1(idValue).asInstanceOf[Any])
    ).asInstanceOf[Builder]
  private inline def builderState1(idValue: IdInput): AfterStep1 =
    new ValidatedBuilderSelectable[ValidatingUser, Any, (code: String)](
      Tuple1((codeValue: CodeInput) => buildValidationFromValues(idValue, codeValue).asInstanceOf[Any])
    ).asInstanceOf[AfterStep1]
  private inline def builderState2(idValue: IdInput, codeValue: CodeInput): AfterStep2 = buildValidationFromValues(idValue, codeValue)
  private def buildValidationFromValues(idValue: IdInput, codeValue: CodeInput): zio.prelude.ZValidation[Nothing, ?, ValidatingUser] =
    zio.prelude.Validation.validateWith(
      validateId(idValue),
      validateCode(codeValue)
    )((idValidated, codeValidated) => ValidatingUser(idValidated, codeValidated))
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  private val smartConstructorMode: builders.configuration.SmartConstructorMode = builders.configuration.SmartConstructorMode.ZValidation
  // format: on
}
