import builders.configuration.*

@GenerateBuilder(
  style = BuilderStyle.Validating,
  pathMode = PathMode.FullCollectionAware,
  primitivePolicy = PrimitivePolicy.PrimitiveAndWrappedIfDerivable
)
case class ValidatingUser(id: Int, code: String)

object ValidatingUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Validating
  private val modeTag: String = "validating"
  private val builderApi: Any = api.ValidatedBuilderGenerator.builder[ValidatingUser]
  private type Builder = api.ValidatedBuilderSelectable[ValidatingUser, ?, (id: Int, code: String)]
  def builder: Builder = api.ValidatedBuilderGenerator.builder[ValidatingUser]
  def builderAllow: Builder = api.ValidatedBuilderGenerator.builderAllow[ValidatingUser]
  def builderNoAllow: Builder = api.ValidatedBuilderGenerator.builderNoAllow[ValidatingUser]
  private def derived: api.ValidatedBuilderGenerator[ValidatingUser] = api.ValidatedBuilderGenerator.derived[ValidatingUser]
  private def derivedAllow: api.ValidatedBuilderGenerator[ValidatingUser] = api.ValidatedBuilderGenerator.derivedAllow[ValidatingUser]
  private def derivedNoAllow: api.ValidatedBuilderGenerator[ValidatingUser] = api.ValidatedBuilderGenerator.derivedNoAllow[ValidatingUser]
  private def builderRef: Builder = builder
  private def builderAllowRef: Any = builderAllow
  private def builderNoAllowRef: Any = builderNoAllow
  private type IdInput = Int
  private type CodeInput = String
  private type AfterStep1 = api.ValidatedBuilderSelectable[ValidatingUser, ?, (code: CodeInput)]
  private type AfterStep2 = zio.prelude.ZValidation[Nothing, ?, ValidatingUser]
  private def fieldStep1Id(current: Builder, input: IdInput): AfterStep1 = {
    current.`id`(input)
  }
  private val idStepName: String = "id"
  private def fieldStep2Code(current: AfterStep1, input: CodeInput): AfterStep2 = {
    current.`code`(input)
  }
  private val codeStepName: String = "code"
  private val fieldSteps: List[String] = List(idStepName, codeStepName)
  private def buildValidationFromValues(idValue: IdInput, codeValue: CodeInput): zio.prelude.ZValidation[Nothing, ?, ValidatingUser] = {
    val afterStep1: AfterStep1 = fieldStep1Id(builder, idValue)
    val afterStep2: AfterStep2 = fieldStep2Code(afterStep1, codeValue)
    afterStep2
  }
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}
