package builders.scalafix

import scala.meta._
import scalafix.v1._
import java.nio.file.{Path, Paths}

class GenerateBuildersRule extends SemanticRule("GenerateBuildersRule") {
  override def fix(implicit doc: SemanticDocument): Patch = {
    val sourceDir = sourceDirectory(doc)
    val existingObjects = doc.tree.collect { case obj: Defn.Object => obj.name.value -> obj }.toMap

    doc.tree.collect { case cls: Defn.Class => cls }.foldLeft(Patch.empty) { (acc, cls) =>
      val className = cls.name.value
      if (!hasGenerateBuilderAnnotation(cls)) {
        acc
      } else {
        val args = annotationArguments(cls)
        val decoded = GenerateBuilderAnnotationDecoder.decode(args).toOption.getOrElse(DecodedGenerateBuilder.default)
        val fields = classFields(cls, sourceDir, decoded)
        val generated = GenerateBuilderCompanionRenderer.render(className, fields, decoded)
        existingObjects.get(className) match {
          case None =>
            acc + Patch.addRight(cls, "\n\n" + generated)
          case Some(existingObject) if isGeneratedCompanion(existingObject) =>
            acc + Patch.replaceTree(existingObject, generated.trim)
          case Some(_) =>
            acc
        }
      }
    }
  }

  private def isGeneratedCompanion(obj: Defn.Object)(implicit doc: SemanticDocument): Boolean = {
    val inputText = doc.input.text
    val text =
      if (obj.pos.start >= 0 && obj.pos.end <= inputText.length && obj.pos.start < obj.pos.end) {
        inputText.substring(obj.pos.start, obj.pos.end)
      } else {
        ""
      }
    text.contains("generated by GenerateBuildersRule") ||
    (text.contains("format: off") && text.contains("format: on"))
  }

  private def sourceDirectory(doc: SemanticDocument): Option[Path] = {
    doc.input match {
      case input: Input.File =>
        Option(input.path.toNIO.getParent)
      case input: Input.VirtualFile =>
        scala.util.Try(Paths.get(input.path)).toOption.flatMap(path => Option(path.getParent))
      case _ =>
        None
    }
  }

  private def hasGenerateBuilderAnnotation(cls: Defn.Class)(implicit doc: SemanticDocument): Boolean = {
    cls.mods.exists {
      case Mod.Annot(init) =>
        GenerateBuildersRuleLogic.isGenerateBuilderAnnotation(init, init.symbol.value)
      case _ =>
        false
    }
  }

  private def annotationArguments(cls: Defn.Class)(implicit doc: SemanticDocument): Map[String, String] = {
    cls.mods.collectFirst {
      case Mod.Annot(init) if GenerateBuildersRuleLogic.isGenerateBuilderAnnotation(init, init.symbol.value) =>
        GenerateBuildersRuleLogic.annotationArguments(init)
    }.getOrElse(Map.empty)
  }

  private def classFields(cls: Defn.Class, sourceDir: Option[Path], options: DecodedGenerateBuilder): List[GenerateBuilderCompanionRenderer.ClassField] = {
    cls.ctor.paramClauses.flatMap(_.values).toList.map { param =>
      val fieldName = param.name.value
      val fieldType = param.decltpe.map(_.syntax).getOrElse("Any")
      val defaultExpr = param.default.map(_.syntax)
      val discoveredSmartCtor = GenerateBuilderSmartCtorDiscovery.discoverFromPath(
        fieldType,
        sourceDir,
        options.smartConstructorMode,
        enableEffectConstructors = options.style == BuilderStyle.Effect
      )
      GenerateBuilderCompanionRenderer.ClassField(
        fieldName,
        fieldType,
        smartCtorMethodName = discoveredSmartCtor.map(_.methodName),
        smartCtorResultKind = discoveredSmartCtor.map(_.resultKind),
        smartCtorZioEnvironmentTypeExpr = discoveredSmartCtor.flatMap(_.zioEnvironmentTypeExpr),
        smartCtorZioErrorTypeExpr = discoveredSmartCtor.flatMap(_.zioErrorTypeExpr),
        smartCtorInputTypeExpr = discoveredSmartCtor.flatMap(_.inputTypeExpr),
        defaultExpr = defaultExpr
      )
    }
  }
}
