package builders.scalafix

object GenerateBuilderCompanionRenderer {
  final case class ClassField(
    name: String,
    typeExpr: String,
    smartCtorMethodName: Option[String] = None,
    defaultExpr: Option[String] = None
  )
  private val RuleVersion: String = "0.1.0-SNAPSHOT"

  def render(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val styleExpr = styleToExpr(options.style)
    val modeTag = styleToTag(options.style)
    val primitivePolicyExpr = primitivePolicyToExpr(options.primitivePolicy)
    val pathModeExpr = pathModeToExpr(options.pathMode)
    val effectModeExpr = effectModeToExpr(options.effectMode)
    val conversionModeExpr = conversionModeToExpr(options.conversionMode)
    val staleCheckModeExpr = staleCheckModeToExpr(options.staleCheckMode)
    val mergeModeExpr = mergeModeToExpr(options.mergeMode)
    val builderApiExpr = builderApiExpression(className, options)
    val builderMembers = styleSpecificBuilderMembers(className, fields, options)

    s"""object $className {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "$RuleVersion"
  private val style: builders.configuration.BuilderStyle = $styleExpr
  private val modeTag: String = \"$modeTag\"
  private val builderApi: Any = $builderApiExpr
  $builderMembers
  private val primitivePolicy: builders.configuration.PrimitivePolicy = $primitivePolicyExpr
  private val pathMode: builders.configuration.PathMode = $pathModeExpr
  private val effectMode: builders.configuration.EffectMode = $effectModeExpr
  private val conversionMode: builders.configuration.ConversionMode = $conversionModeExpr
  private val staleCheckMode: builders.configuration.StaleCheckMode = $staleCheckModeExpr
  private val mergeMode: builders.configuration.MergeMode = $mergeModeExpr
  // format: on
}
"""
  }

  private def styleToExpr(style: BuilderStyle): String = style match {
    case BuilderStyle.Simple =>
      "builders.configuration.BuilderStyle.Simple"
    case BuilderStyle.Validating =>
      "builders.configuration.BuilderStyle.Validating"
    case BuilderStyle.Effect =>
      "builders.configuration.BuilderStyle.Effect"
  }

  private def styleToTag(style: BuilderStyle): String = style match {
    case BuilderStyle.Simple =>
      "simple"
    case BuilderStyle.Validating =>
      "validating"
    case BuilderStyle.Effect =>
      "effect"
  }

  private def builderApiExpression(className: String, options: DecodedGenerateBuilder): String = options.style match {
    case BuilderStyle.Simple =>
      options.builderMethodName
    case BuilderStyle.Validating =>
      s"api.ValidatedBuilderGenerator.builder[$className]"
    case BuilderStyle.Effect =>
      // Effect mode currently reuses validating API until backend-specific effects are implemented.
      s"api.ValidatedBuilderGenerator.builder[$className]"
  }

  private def styleSpecificBuilderMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = options.style match {
    case BuilderStyle.Simple =>
      val fieldMembers = renderSimpleFieldMembers(className, fields, options)
      s"""$fieldMembers"""
    case BuilderStyle.Validating =>
      val terminalType = s"zio.prelude.ZValidation[Nothing, ?, $className]"
      val publicBuilderMethodName = options.builderMethodName
      val allowMethod = publicBuilderMethodName + "Allow"
      val noAllowMethod = publicBuilderMethodName + "NoAllow"
      val fieldMembers = renderGenericFieldMembers(className, fields, publicBuilderMethodName, terminalType = terminalType, buildMethodName = "buildValidationFromValues")
      val extraPublicBuilders =
        if (options.generateExtraVariants) {
          s"""  def $allowMethod: Builder = api.ValidatedBuilderGenerator.builderAllow[$className]
  def $noAllowMethod: Builder = api.ValidatedBuilderGenerator.builderNoAllow[$className]"""
        } else {
          ""
        }
      val privateRefs =
        if (options.generateExtraVariants) {
          s"""  private def ${allowMethod}Ref: Any = $allowMethod
  private def ${noAllowMethod}Ref: Any = $noAllowMethod"""
        } else {
          ""
        }
      s"""private type Builder = api.ValidatedBuilderSelectable[$className, ?, (${renderBuilderInputTuple(fields)})]
  def $publicBuilderMethodName: Builder = api.ValidatedBuilderGenerator.builder[$className]
$extraPublicBuilders
  private def derived: api.ValidatedBuilderGenerator[$className] = api.ValidatedBuilderGenerator.derived[$className]
  private def derivedAllow: api.ValidatedBuilderGenerator[$className] = api.ValidatedBuilderGenerator.derivedAllow[$className]
  private def derivedNoAllow: api.ValidatedBuilderGenerator[$className] = api.ValidatedBuilderGenerator.derivedNoAllow[$className]
  private def builderRef: Builder = $publicBuilderMethodName
$privateRefs
$fieldMembers"""
    case BuilderStyle.Effect =>
      val terminalType = s"zio.prelude.ZValidation[Nothing, ?, $className]"
      val publicBuilderMethodName = options.builderMethodName
      val effectMethodName = publicBuilderMethodName + "Effect"
      val fieldMembers = renderGenericFieldMembers(
        className,
        fields,
        if (options.generateExtraVariants) effectMethodName else publicBuilderMethodName,
        terminalType = terminalType,
        buildMethodName = "buildEffectFromValues"
      )
      val effectMethodDef =
        if (options.generateExtraVariants) {
          s"def $effectMethodName: Builder = $publicBuilderMethodName"
        } else {
          ""
        }
      val effectRefDef =
        if (options.generateExtraVariants) {
          s"private def ${effectMethodName}Ref: Any = $effectMethodName"
        } else {
          ""
        }
      s"""private type Builder = api.ValidatedBuilderSelectable[$className, ?, (${renderBuilderInputTuple(fields)})]
  def $publicBuilderMethodName: Builder = api.ValidatedBuilderGenerator.builder[$className]
  $effectMethodDef
  private def derived: api.ValidatedBuilderGenerator[$className] = api.ValidatedBuilderGenerator.derived[$className]
  private def builderRef: Builder = $publicBuilderMethodName
  // Effect backend is currently modeled through the validated builder seam.
  $effectRefDef
$fieldMembers"""
  }

  private def primitivePolicyToExpr(value: PrimitivePolicy): String = value match {
    case PrimitivePolicy.WrappedOnly =>
      "builders.configuration.PrimitivePolicy.WrappedOnly"
    case PrimitivePolicy.PrimitiveAndWrappedIfDerivable =>
      "builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable"
    case PrimitivePolicy.PrimitiveOnly =>
      "builders.configuration.PrimitivePolicy.PrimitiveOnly"
  }

  private def pathModeToExpr(value: PathMode): String = value match {
    case PathMode.Disabled =>
      "builders.configuration.PathMode.Disabled"
    case PathMode.CustomPrefixOnly =>
      "builders.configuration.PathMode.CustomPrefixOnly"
    case PathMode.FullCollectionAware =>
      "builders.configuration.PathMode.FullCollectionAware"
  }

  private def effectModeToExpr(value: EffectMode): String = value match {
    case EffectMode.ValidationOnly =>
      "builders.configuration.EffectMode.ValidationOnly"
    case EffectMode.AbstractCapability =>
      "builders.configuration.EffectMode.AbstractCapability"
  }

  private def conversionModeToExpr(value: ConversionMode): String = value match {
    case ConversionMode.UseExistingOnly =>
      "builders.configuration.ConversionMode.UseExistingOnly"
    case ConversionMode.SynthesizeIfMissing =>
      "builders.configuration.ConversionMode.SynthesizeIfMissing"
    case ConversionMode.SynthesizeAndExposeHelpers =>
      "builders.configuration.ConversionMode.SynthesizeAndExposeHelpers"
  }

  private def staleCheckModeToExpr(value: StaleCheckMode): String = value match {
    case StaleCheckMode.SignatureHash =>
      "builders.configuration.StaleCheckMode.SignatureHash"
    case StaleCheckMode.StructuralOnly =>
      "builders.configuration.StaleCheckMode.StructuralOnly"
  }

  private def mergeModeToExpr(value: MergeMode): String = value match {
    case MergeMode.GeneratedRegionOnly =>
      "builders.configuration.MergeMode.GeneratedRegionOnly"
    case MergeMode.ReplaceGeneratedMembers =>
      "builders.configuration.MergeMode.ReplaceGeneratedMembers"
  }

  private def renderSimpleFieldMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val publicBuilderMethodName = options.builderMethodName
    if (fields.isEmpty) {
      s"""private type Builder = $className
  def $publicBuilderMethodName: Builder = $className()"""
    } else if (options.simpleOptionalValues == SimpleOptionalValues.OptionalValuesWithEmptyDefaults || options.simpleOptionalValues == SimpleOptionalValues.OptionalValuesFromDefaults) {
      renderSimpleFieldMembersWithOmittedValues(className, fields, publicBuilderMethodName, options.simpleOptionalValues)
    } else {
      val smartEnabledByField = List.fill(fields.size)(false)

      val inputAliases = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        val inputTypeExpr = renderSimpleInputTypeExpr(field, options)
        s"  private type ${capitalize(sanitized)}Input = $inputTypeExpr"
      }

      val afterStepTypeAliases = renderAfterStepTypeAliases(className, fields)
      val builderType = renderSimpleBuilderTypeExpr(className, fields)
      val conversionHelpers = renderSimpleConversionHelpers(fields, smartEnabledByField)
      val stepMethods = renderSimpleStepMethods(className, fields, smartEnabledByField)
      val firstParamName = sanitizeFieldName(fields.head.name)
      val firstParamTypeAlias = s"${capitalize(firstParamName)}Input"
      val builderImpl = s"($firstParamName= ($firstParamName: $firstParamTypeAlias) => step1($firstParamName))"

      (
        List(
          s"private type Builder = $builderType",
          s"  inline def $publicBuilderMethodName: Builder = $builderImpl"
        ) ++ inputAliases ++ afterStepTypeAliases ++ conversionHelpers ++ stepMethods
      ).mkString("\n")
    }
  }

  private def renderSimpleInputTypeExpr(field: ClassField, options: DecodedGenerateBuilder): String = {
    field.typeExpr
  }

  private def isSimpleSmartConversionEnabled(options: DecodedGenerateBuilder, field: ClassField): Boolean = {
    false
  }

  private def renderSimpleConversionHelpers(fields: List[ClassField], smartEnabledByField: List[Boolean]): List[String] = {
    Nil
  }

  private def renderSimpleStepMethods(className: String, fields: List[ClassField], smartEnabledByField: List[Boolean]): List[String] = {
    fields.indices.map { index =>
      val methodName = s"step${index + 1}"
      val params = fields.take(index + 1).map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"$sanitized: ${capitalize(sanitized)}Input"
      }.mkString(", ")
      val returnType = s"AfterStep${index + 1}"
      val body =
        if (index == fields.size - 1) {
          val args = fields.zipWithIndex.map {
            case (field, argIndex) =>
              val sanitized = sanitizeFieldName(field.name)
              if (smartEnabledByField(argIndex)) {
                s"summon[SimpleSmartConstructor[${capitalize(sanitized)}Input, ${field.typeExpr}]].fromInput($sanitized)"
              } else {
                sanitized
              }
          }.mkString(", ")
          s"$className($args)"
        } else {
          val nextField = fields(index + 1)
          val nextName = sanitizeFieldName(nextField.name)
          val previousArgs = fields.take(index + 1).map(field => sanitizeFieldName(field.name))
          val allArgs = (previousArgs :+ nextName).mkString(", ")
          s"($nextName= ($nextName: ${capitalize(nextName)}Input) => step${index + 2}($allArgs))"
        }
      s"  private inline def $methodName($params): $returnType = $body"
    }.toList
  }

  private def renderAfterStepTypeAliases(className: String, fields: List[ClassField]): List[String] = {
    val inputTypeNames = fields.map { field =>
      capitalize(sanitizeFieldName(field.name)) + "Input"
    }

    val afterTypeNames = (1 to fields.size).map(index => s"AfterStep$index")

    afterTypeNames.reverse.zipWithIndex.map {
      case (afterTypeName, reverseIndex) =>
        val stepIndex = fields.size - reverseIndex
        val rhs = if (stepIndex == fields.size) {
          className
        } else {
          val nextLabel = sanitizeFieldName(fields(stepIndex).name)
          val nextInput = inputTypeNames(stepIndex)
          val nextAfter = s"AfterStep${stepIndex + 1}"
          s"($nextLabel: $nextInput => $nextAfter)"
        }
        s"  private type $afterTypeName = $rhs"
    }.reverse.toList
  }

  private def renderSimpleBuilderTypeExpr(className: String, fields: List[ClassField]): String = {
    if (fields.isEmpty) {
      className
    } else {
      val first = fields.head
      val firstName = sanitizeFieldName(first.name)
      s"($firstName: ${capitalize(firstName)}Input => AfterStep1)"
    }
  }

  private final case class SimpleFieldPlan(
    field: ClassField,
    sanitizedName: String,
    inputTypeExpr: String,
    ctorValueFromInput: String => String,
    defaultCtorValueExpr: Option[String]
  ) {
    def omittable: Boolean = defaultCtorValueExpr.nonEmpty
  }

  private def renderSimpleFieldMembersWithOmittedValues(
    className: String,
    fields: List[ClassField],
    publicBuilderMethodName: String,
    mode: SimpleOptionalValues
  ): String = {
    val plans = fields.map(field => simpleFieldPlan(field, mode))
    val inputAliases = plans.map { plan =>
      s"  private type ${capitalize(plan.sanitizedName)}Input = ${plan.inputTypeExpr}"
    }

    val afterStepTypeAliases = (1 to plans.size).toList.map { index =>
      s"  private type AfterStep$index = ${renderSimpleOmittedStateType(index, plans, className)}"
    }

    val stateMethods = (0 to plans.size).toList.map { index =>
      renderSimpleOmittedStateMethod(index, plans, className)
    }

    (
      List(
        s"private type Builder = ${renderSimpleOmittedStateType(0, plans, className)}",
        s"  inline def $publicBuilderMethodName: Builder = state0()"
      ) ++ inputAliases ++ afterStepTypeAliases ++ stateMethods
    ).mkString("\n")
  }

  private def renderSimpleOmittedStateType(index: Int, plans: List[SimpleFieldPlan], className: String): String = {
    if (index >= plans.size) {
      className
    } else {
      val setterActions = omittedSetterTargets(index, plans).map { targetIndex =>
        val targetPlan = plans(targetIndex)
        val nextType = afterStepTypeName(targetIndex + 1, plans)
        s"${targetPlan.sanitizedName}: ${capitalize(targetPlan.sanitizedName)}Input => $nextType"
      }
      val buildAction =
        if (canBuildFrom(index, plans)) {
          List(s"build: () => ${afterStepTypeName(plans.size, plans)}")
        } else {
          Nil
        }
      (setterActions ++ buildAction).mkString("(", ", ", ")")
    }
  }

  private def renderSimpleOmittedStateMethod(index: Int, plans: List[SimpleFieldPlan], className: String): String = {
    val methodName = s"state$index"
    val stateType = afterStepTypeName(index, plans)
    val params = plans.take(index).map { plan =>
      s"${plan.sanitizedName}: ${plan.field.typeExpr}"
    }.mkString(", ")
    val signature =
      if (params.isEmpty) {
        s"  private inline def $methodName(): $stateType"
      } else {
        s"  private inline def $methodName($params): $stateType"
      }

    val body =
      if (index >= plans.size) {
        val args = plans.map(_.sanitizedName).mkString(", ")
        s"$className($args)"
      } else {
        val setterEntries = omittedSetterTargets(index, plans).map { targetIndex =>
          val targetPlan = plans(targetIndex)
          val currentArgNames = plans.take(index).map(_.sanitizedName)
          val skippedDefaults = plans.slice(index, targetIndex).map { skipped =>
            skipped.defaultCtorValueExpr.getOrElse(skipped.sanitizedName)
          }
          val selectedArg = targetPlan.ctorValueFromInput(targetPlan.sanitizedName)
          val allArgs = (currentArgNames ++ skippedDefaults :+ selectedArg).mkString(", ")
          s"${targetPlan.sanitizedName}= (${targetPlan.sanitizedName}: ${capitalize(targetPlan.sanitizedName)}Input) => state${targetIndex + 1}($allArgs)"
        }
        val buildEntry =
          if (canBuildFrom(index, plans)) {
            val currentArgNames = plans.take(index).map(_.sanitizedName)
            val defaultArgs = plans.drop(index).map { plan =>
              plan.defaultCtorValueExpr.getOrElse(plan.sanitizedName)
            }
            val args = (currentArgNames ++ defaultArgs).mkString(", ")
            List(s"build= () => state${plans.size}($args)")
          } else {
            Nil
          }
        (setterEntries ++ buildEntry).mkString("(", ", ", ")")
      }

    s"$signature = $body"
  }

  private def omittedSetterTargets(index: Int, plans: List[SimpleFieldPlan]): List[Int] = {
    if (index >= plans.size) {
      Nil
    } else {
      val targets = scala.collection.mutable.ListBuffer[Int](index)
      var probe = index + 1
      var canSkip = true
      while (probe < plans.size && canSkip) {
        canSkip = plans(probe - 1).omittable
        if (canSkip) {
          targets += probe
          probe += 1
        }
      }
      targets.toList
    }
  }

  private def canBuildFrom(index: Int, plans: List[SimpleFieldPlan]): Boolean = {
    plans.drop(index).forall(_.omittable)
  }

  private def afterStepTypeName(index: Int, plans: List[SimpleFieldPlan]): String = {
    if (index == 0) {
      "Builder"
    } else {
      s"AfterStep$index"
    }
  }

  private def simpleFieldPlan(field: ClassField, mode: SimpleOptionalValues): SimpleFieldPlan = {
    val sanitizedName = sanitizeFieldName(field.name)
    val fieldType = field.typeExpr.trim
    val normalized = fieldType.replace(" ", "")
    val optionRegex = """^(?:scala\.)?Option\[(.+)\]$""".r
    val optionalRegex = """^(?:java\.util\.)?Optional\[(.+)\]$""".r
    val optionalIntRegex = """^(?:java\.util\.)?OptionalInt$""".r
    val optionalLongRegex = """^(?:java\.util\.)?OptionalLong$""".r
    val optionalDoubleRegex = """^(?:java\.util\.)?OptionalDouble$""".r

    normalized match {
      case optionRegex(inner) =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = inner,
          ctorValueFromInput = input => s"Some($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "None")
        )
      case optionalRegex(inner) =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = inner,
          ctorValueFromInput = input => s"java.util.Optional.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.Optional.empty()")
        )
      case optionalIntRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Int",
          ctorValueFromInput = input => s"java.util.OptionalInt.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalInt.empty()")
        )
      case optionalLongRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Long",
          ctorValueFromInput = input => s"java.util.OptionalLong.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalLong.empty()")
        )
      case optionalDoubleRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Double",
          ctorValueFromInput = input => s"java.util.OptionalDouble.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalDouble.empty()")
        )
      case _ =>
        nullableInnerType(fieldType) match {
          case Some(innerType) =>
            SimpleFieldPlan(
              field = field,
              sanitizedName = sanitizedName,
              inputTypeExpr = innerType,
              ctorValueFromInput = input => input,
              defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "null")
            )
          case None =>
            SimpleFieldPlan(
              field = field,
              sanitizedName = sanitizedName,
              inputTypeExpr = field.typeExpr,
              ctorValueFromInput = input => input,
              defaultCtorValueExpr = None
            )
        }
    }
  }

  private def simpleOptionalDefault(mode: SimpleOptionalValues, declaredDefault: Option[String], emptyDefault: String): Option[String] = {
    mode match {
      case SimpleOptionalValues.OptionalValuesWithEmptyDefaults =>
        Some(emptyDefault)
      case SimpleOptionalValues.OptionalValuesFromDefaults =>
        declaredDefault
      case SimpleOptionalValues.ExplicitOptionalValues =>
        None
    }
  }

  private def nullableInnerType(rawType: String): Option[String] = {
    val parts = rawType.split("\\|").map(_.trim).filter(_.nonEmpty).toList
    if (parts.size == 2) {
      val nullAliases = Set("Null", "scala.Null")
      val nonNullParts = parts.filterNot(nullAliases.contains)
      if (nonNullParts.size == 1) {
        Some(nonNullParts.head)
      } else {
        None
      }
    } else {
      None
    }
  }

  private def renderGenericFieldMembers(
    className: String,
    fields: List[ClassField],
    startStateExpr: String,
    terminalType: String,
    buildMethodName: String
  ): String = {
    if (fields.isEmpty) {
      s"""  private val fieldSteps: List[String] = Nil
  private def $buildMethodName(): $terminalType =
    $startStateExpr.asInstanceOf[$terminalType]"""
    } else {
      val inputAliases = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"  private type ${capitalize(sanitized)}Input = ${field.typeExpr}"
      }

      val afterStepTypeAliases = renderGenericAfterStepTypeAliases(className, fields, terminalType)

      val stepMethodsAndNames = fields.zipWithIndex.flatMap {
        case (field, index) =>
          val sanitized = sanitizeFieldName(field.name)
          val displayName = escapeForString(field.name)
          val stepName = s"fieldStep${index + 1}${capitalize(sanitized)}"
          val inputTypeAlias = s"${capitalize(sanitized)}Input"
          val currentStateType = if (index == 0) "Builder" else s"AfterStep$index"
          val nextStateType = s"AfterStep${index + 1}"
          List(
            s"  private def $stepName(current: $currentStateType, input: $inputTypeAlias): $nextStateType = {",
            s"    current.`$displayName`(input)",
            "  }",
            s"  private val ${sanitized}StepName: String = \"$displayName\""
          )
      }

      val stepList = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"${sanitized}StepName"
      }.mkString(", ")

      val parameterDecl = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"${sanitized}Value: ${capitalize(sanitized)}Input"
      }.mkString(", ")

      val stateLines = fields.zipWithIndex.map {
        case (field, index) =>
          val sanitized = sanitizeFieldName(field.name)
          val stepName = s"fieldStep${index + 1}${capitalize(sanitized)}"
          val previous = if (index == 0) startStateExpr else s"afterStep$index"
          val current = s"afterStep${index + 1}"
          s"    val $current: AfterStep${index + 1} = $stepName($previous, ${sanitized}Value)"
      }

      val buildHelper = (
        List(
          s"  private val fieldSteps: List[String] = List($stepList)",
          s"  private def $buildMethodName($parameterDecl): $terminalType = {"
        ) ++ stateLines ++ List(
          s"    afterStep${fields.size}",
          "  }"
        )
      ).mkString("\n")

      (inputAliases ++ afterStepTypeAliases ++ stepMethodsAndNames :+ buildHelper).mkString("\n")
    }
  }

  private def renderGenericAfterStepTypeAliases(className: String, fields: List[ClassField], terminalType: String): List[String] = {
    val inputTypeNames = fields.map { field =>
      capitalize(sanitizeFieldName(field.name)) + "Input"
    }

    val afterTypeNames = (1 to fields.size).map(index => s"AfterStep$index")

    afterTypeNames.reverse.zipWithIndex.map {
      case (afterTypeName, reverseIndex) =>
        val stepIndex = fields.size - reverseIndex
        val rhs = if (stepIndex == fields.size) {
          terminalType
        } else {
          val remaining = fields.drop(stepIndex).zip(inputTypeNames.drop(stepIndex)).map {
            case (field, inputName) =>
              s"${sanitizeFieldName(field.name)}: $inputName"
          }.mkString(", ")
          s"api.ValidatedBuilderSelectable[$className, ?, ($remaining)]"
        }
        s"  private type $afterTypeName = $rhs"
    }.reverse.toList
  }

  private def renderBuilderInputTuple(fields: List[ClassField]): String = {
    fields.map { field =>
      val sanitized = sanitizeFieldName(field.name)
      s"$sanitized: ${field.typeExpr}"
    }.mkString(", ")
  }

  private def sanitizeFieldName(value: String): String = {
    val cleaned = value.replaceAll("[^A-Za-z0-9_]", "")
    val base = if (cleaned.isEmpty) "field" else cleaned
    if (base.headOption.exists(_.isDigit)) {
      "field" + base
    } else {
      base
    }
  }

  private def capitalize(value: String): String = {
    if (value.isEmpty) {
      value
    } else {
      value.substring(0, 1).toUpperCase + value.substring(1)
    }
  }

  private def escapeForString(value: String): String = {
    value.replace("\\", "\\\\").replace("\"", "\\\"")
  }
}
