package builders.scalafix

import java.nio.file.Files
import java.nio.file.Path

object GenerateBuilderTextRewriter {
  private final case class AnnotatedCaseClassMatch(argsRaw: String, className: String, fieldsRaw: String)

  def rewrite(source: String): String = {
    val matches = findAnnotatedCaseClasses(source)
    if (matches.isEmpty) {
      source
    } else {
      val replacements = matches.flatMap { m =>
        val argsRaw = m.argsRaw
        val className = m.className
        val fieldsRaw = m.fieldsRaw
        val args = parseArguments(argsRaw)
        val decoded = GenerateBuilderAnnotationDecoder.decode(args).toOption.getOrElse(DecodedGenerateBuilder.default)
        val fields = parseFields(fieldsRaw)
        val generated = GenerateBuilderCompanionRenderer.render(className, fields, decoded)
        findCompanionRange(source, className) match {
          case Some((start, end)) if isGeneratedCompanion(source.substring(start, end)) =>
            Some((start, end, generated.trim))
          case Some(_) =>
            None
          case None =>
            Some((-1, -1, generated.trim))
        }
      }

      val (updates, additions) = replacements.partition(_._1 >= 0)
      val updatedSource = updates.sortBy(-_._1).foldLeft(source) {
        case (acc, (start, end, replacement)) =>
          acc.substring(0, start) + replacement + acc.substring(end)
      }

      if (additions.isEmpty) updatedSource
      else {
        val suffix = additions.map(_._3).mkString("\n\n")
        val normalized = updatedSource.stripTrailing()
        normalized + "\n\n" + suffix
      }
    }
  }

  def rewriteFile(path: Path): Unit = {
    val original = Files.readString(path)
    val rewritten = rewrite(original)
    if (rewritten != original) {
      Files.writeString(path, rewritten)
    }
  }

  private def findCompanionRange(source: String, className: String): Option[(Int, Int)] = {
    val objectPattern = ("""(?m)^\s*object\s+""" + java.util.regex.Pattern.quote(className) + """\b""").r
    objectPattern.findFirstMatchIn(source).flatMap { m =>
      val objectStart = m.start
      val openBraceIndex = source.indexOf('{', m.end)
      if (openBraceIndex < 0) {
        None
      } else {
        var index = openBraceIndex
        var depth = 0
        var inString = false
        var escaped = false
        while (index < source.length) {
          val ch = source.charAt(index)
          if (inString) {
            if (escaped) escaped = false
            else if (ch == '\\') escaped = true
            else if (ch == '"') inString = false
          } else {
            if (ch == '"') inString = true
            else if (ch == '{') depth += 1
            else if (ch == '}') {
              depth -= 1
              if (depth == 0) {
                return Some((objectStart, index + 1))
              }
            }
          }
          index += 1
        }
        None
      }
    }
  }

  private def isGeneratedCompanion(companionText: String): Boolean = {
    companionText.contains("generated by GenerateBuildersRule") ||
    (companionText.contains("format: off") && companionText.contains("format: on"))
  }

  private def parseArguments(raw: String): Map[String, String] = {
    splitTopLevel(raw, ',')
      .toList
      .map(_.trim)
      .filter(_.nonEmpty)
      .flatMap { pair =>
        findTopLevelChar(pair, '=') match {
          case Some(eqIndex) =>
            val key = pair.substring(0, eqIndex).trim
            val value = pair.substring(eqIndex + 1).trim
            if (key.nonEmpty && value.nonEmpty) Some(key -> value) else None
          case None =>
            None
        }
      }
      .toMap
  }

  private def parseFields(raw: String): List[GenerateBuilderCompanionRenderer.ClassField] = {
    splitTopLevel(raw, ',')
      .toList
      .map(_.trim)
      .filter(_.nonEmpty)
      .flatMap { part =>
        findTopLevelChar(part, ':') match {
          case Some(colonIndex) =>
            val namePart = part.substring(0, colonIndex).trim
            val typeAndDefault = part.substring(colonIndex + 1).trim
            val fieldName = extractFieldName(namePart)
            if (fieldName.isEmpty || typeAndDefault.isEmpty) {
              None
            } else {
              findTopLevelChar(typeAndDefault, '=') match {
                case Some(eqIndex) =>
                  val typeExpr = typeAndDefault.substring(0, eqIndex).trim
                  val defaultExpr = typeAndDefault.substring(eqIndex + 1).trim
                  if (typeExpr.nonEmpty && defaultExpr.nonEmpty) {
                    Some(GenerateBuilderCompanionRenderer.ClassField(fieldName, typeExpr, defaultExpr = Some(defaultExpr)))
                  } else {
                    None
                  }
                case None =>
                  Some(GenerateBuilderCompanionRenderer.ClassField(fieldName, typeAndDefault))
              }
            }
          case None =>
            None
        }
      }
  }

  private def findAnnotatedCaseClasses(source: String): List[AnnotatedCaseClassMatch] = {
    val annotationToken = "@GenerateBuilder"
    var index = 0
    val matches = scala.collection.mutable.ListBuffer.empty[AnnotatedCaseClassMatch]

    while (index >= 0 && index < source.length) {
      val at = source.indexOf(annotationToken, index)
      if (at < 0) {
        index = -1
      } else {
        var cursor = at + annotationToken.length
        cursor = skipWhitespace(source, cursor)

        val argsRawAndCursor =
          if (cursor < source.length && source.charAt(cursor) == '(') {
            findBalancedRegion(source, cursor, '(', ')').map {
              case (open, close) =>
                (source.substring(open + 1, close), close + 1)
            }
          } else {
            Some(("", cursor))
          }

        argsRawAndCursor match {
          case Some((argsRaw, afterArgs)) =>
            val afterWs = skipWhitespace(source, afterArgs)
            if (startsWithWord(source, afterWs, "case") && startsWithWord(source, skipWhitespace(source, afterWs + 4), "class")) {
              val classKeywordStart = skipWhitespace(source, afterWs + 4)
              val classNameStart = skipWhitespace(source, classKeywordStart + 5)
              val classNameEnd = readIdentifierEnd(source, classNameStart)
              if (classNameEnd > classNameStart) {
                val className = source.substring(classNameStart, classNameEnd)
                val openParenIndex = source.indexOf('(', classNameEnd)
                if (openParenIndex >= 0) {
                  findBalancedRegion(source, openParenIndex, '(', ')') match {
                    case Some((open, close)) =>
                      val fieldsRaw = source.substring(open + 1, close)
                      matches += AnnotatedCaseClassMatch(argsRaw, className, fieldsRaw)
                      index = close + 1
                    case None =>
                      index = at + annotationToken.length
                  }
                } else {
                  index = at + annotationToken.length
                }
              } else {
                index = at + annotationToken.length
              }
            } else {
              index = at + annotationToken.length
            }
          case None =>
            index = at + annotationToken.length
        }
      }
    }

    matches.toList
  }

  private def splitTopLevel(raw: String, separator: Char): List[String] = {
    val out = scala.collection.mutable.ListBuffer.empty[String]
    var start = 0
    var round = 0
    var square = 0
    var curly = 0
    var inString = false
    var escaped = false
    var i = 0
    while (i < raw.length) {
      val ch = raw.charAt(i)
      if (inString) {
        if (escaped) escaped = false
        else if (ch == '\\') escaped = true
        else if (ch == '"') inString = false
      } else {
        ch match {
          case '"' => inString = true
          case '(' => round += 1
          case ')' => if (round > 0) round -= 1
          case '[' => square += 1
          case ']' => if (square > 0) square -= 1
          case '{' => curly += 1
          case '}' => if (curly > 0) curly -= 1
          case c if c == separator && round == 0 && square == 0 && curly == 0 =>
            out += raw.substring(start, i)
            start = i + 1
          case _ =>
        }
      }
      i += 1
    }
    out += raw.substring(start)
    out.toList
  }

  private def findTopLevelChar(raw: String, target: Char): Option[Int] = {
    var round = 0
    var square = 0
    var curly = 0
    var inString = false
    var escaped = false
    var i = 0
    while (i < raw.length) {
      val ch = raw.charAt(i)
      if (inString) {
        if (escaped) escaped = false
        else if (ch == '\\') escaped = true
        else if (ch == '"') inString = false
      } else {
        ch match {
          case '"' => inString = true
          case '(' => round += 1
          case ')' => if (round > 0) round -= 1
          case '[' => square += 1
          case ']' => if (square > 0) square -= 1
          case '{' => curly += 1
          case '}' => if (curly > 0) curly -= 1
          case c if c == target && round == 0 && square == 0 && curly == 0 =>
            return Some(i)
          case _ =>
        }
      }
      i += 1
    }
    None
  }

  private def extractFieldName(rawNamePart: String): String = {
    val trimmed = rawNamePart.trim
    if (trimmed.isEmpty) {
      ""
    } else {
      val tokens = trimmed.split("\\s+").filter(_.nonEmpty)
      if (tokens.isEmpty) "" else tokens.last
    }
  }

  private def findBalancedRegion(source: String, openIndex: Int, open: Char, close: Char): Option[(Int, Int)] = {
    if (openIndex < 0 || openIndex >= source.length || source.charAt(openIndex) != open) {
      None
    } else {
      var depth = 0
      var inString = false
      var escaped = false
      var i = openIndex
      while (i < source.length) {
        val ch = source.charAt(i)
        if (inString) {
          if (escaped) escaped = false
          else if (ch == '\\') escaped = true
          else if (ch == '"') inString = false
        } else {
          if (ch == '"') inString = true
          else if (ch == open) depth += 1
          else if (ch == close) {
            depth -= 1
            if (depth == 0) {
              return Some((openIndex, i))
            }
          }
        }
        i += 1
      }
      None
    }
  }

  private def skipWhitespace(source: String, from: Int): Int = {
    var i = from
    while (i < source.length && source.charAt(i).isWhitespace) {
      i += 1
    }
    i
  }

  private def startsWithWord(source: String, index: Int, word: String): Boolean = {
    if (index < 0 || index + word.length > source.length) {
      false
    } else {
      val slice = source.substring(index, index + word.length)
      val afterOk = index + word.length == source.length || !source.charAt(index + word.length).isLetterOrDigit && source.charAt(index + word.length) != '_'
      slice == word && afterOk
    }
  }

  private def readIdentifierEnd(source: String, start: Int): Int = {
    if (start >= source.length) {
      start
    } else {
      var i = start
      if (source.charAt(i).isLetter || source.charAt(i) == '_') {
        i += 1
        while (i < source.length && (source.charAt(i).isLetterOrDigit || source.charAt(i) == '_')) {
          i += 1
        }
        i
      } else {
        start
      }
    }
  }
}
