package builders.scalafix

object GenerateBuilderCompanionRenderer {
  sealed trait SmartCtorResultKind
  object SmartCtorResultKind {
    case object Validation extends SmartCtorResultKind
    case object EitherResult extends SmartCtorResultKind
    case object Direct extends SmartCtorResultKind
  }

  final case class ClassField(
    name: String,
    typeExpr: String,
    smartCtorMethodName: Option[String] = None,
    smartCtorResultKind: Option[SmartCtorResultKind] = None,
    smartCtorInputTypeExpr: Option[String] = None,
    defaultExpr: Option[String] = None
  )
  private val RuleVersion: String = "0.1.0-SNAPSHOT"

  def render(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val styleExpr = styleToExpr(options.style)
    val modeTag = styleToTag(options.style)
    val primitivePolicyExpr = primitivePolicyToExpr(options.primitivePolicy)
    val pathModeExpr = pathModeToExpr(options.pathMode)
    val effectModeExpr = effectModeToExpr(options.effectMode)
    val conversionModeExpr = conversionModeToExpr(options.conversionMode)
    val staleCheckModeExpr = staleCheckModeToExpr(options.staleCheckMode)
    val mergeModeExpr = mergeModeToExpr(options.mergeMode)
    val smartConstructorModeExpr = smartConstructorModeToExpr(options.smartConstructorMode)
    val errorCombinationExpr = errorCombinationToExpr(options.combineErrors)
    val effectFailureModeExpr = effectFailureModeToExpr(options.effectFailureMode)
    val generatedCodeShapeExpr = generatedCodeShapeToExpr(options.generatedCodeShape)
    val configurationMembers = renderConfigurationMembers(
      options.style,
      primitivePolicyExpr,
      pathModeExpr,
      effectModeExpr,
      conversionModeExpr,
      staleCheckModeExpr,
      mergeModeExpr,
      smartConstructorModeExpr,
      errorCombinationExpr,
      effectFailureModeExpr,
      generatedCodeShapeExpr
    )
    val builderApiExpr = builderApiExpression(className, options)
    val builderMembers = styleSpecificBuilderMembers(className, fields, options)

    s"""object $className {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "$RuleVersion"
  private val style: builders.configuration.BuilderStyle = $styleExpr
  private val modeTag: String = \"$modeTag\"
  private val builderApi: Any = $builderApiExpr
  $builderMembers
$configurationMembers
  // format: on
}
"""
  }

  private def renderConfigurationMembers(
    style: BuilderStyle,
    primitivePolicyExpr: String,
    pathModeExpr: String,
    effectModeExpr: String,
    conversionModeExpr: String,
    staleCheckModeExpr: String,
    mergeModeExpr: String,
    smartConstructorModeExpr: String,
    errorCombinationExpr: String,
    effectFailureModeExpr: String,
    generatedCodeShapeExpr: String
  ): String = {
    val base = List(
      s"  private val primitivePolicy: builders.configuration.PrimitivePolicy = $primitivePolicyExpr",
      s"  private val pathMode: builders.configuration.PathMode = $pathModeExpr",
      s"  private val effectMode: builders.configuration.EffectMode = $effectModeExpr",
      s"  private val conversionMode: builders.configuration.ConversionMode = $conversionModeExpr",
      s"  private val staleCheckMode: builders.configuration.StaleCheckMode = $staleCheckModeExpr",
      s"  private val mergeMode: builders.configuration.MergeMode = $mergeModeExpr"
    )
    val smart = style match {
      case BuilderStyle.Simple =>
        Nil
      case BuilderStyle.Validating =>
        List(
          s"  private val smartConstructorMode: builders.configuration.SmartConstructorMode = $smartConstructorModeExpr",
          s"  private val combineErrors: builders.configuration.ErrorCombination = $errorCombinationExpr",
          s"  private val generatedCodeShape: builders.configuration.GeneratedCodeShape = $generatedCodeShapeExpr"
        )
      case BuilderStyle.Effect =>
        List(
          s"  private val smartConstructorMode: builders.configuration.SmartConstructorMode = $smartConstructorModeExpr",
          s"  private val combineErrors: builders.configuration.ErrorCombination = $errorCombinationExpr",
          s"  private val effectFailureMode: builders.configuration.EffectFailureMode = $effectFailureModeExpr",
          s"  private val generatedCodeShape: builders.configuration.GeneratedCodeShape = $generatedCodeShapeExpr"
        )
    }

    (base ++ smart).mkString("\n")
  }

  private def styleToExpr(style: BuilderStyle): String = style match {
    case BuilderStyle.Simple =>
      "builders.configuration.BuilderStyle.Simple"
    case BuilderStyle.Validating =>
      "builders.configuration.BuilderStyle.Validating"
    case BuilderStyle.Effect =>
      "builders.configuration.BuilderStyle.Effect"
  }

  private def styleToTag(style: BuilderStyle): String = style match {
    case BuilderStyle.Simple =>
      "simple"
    case BuilderStyle.Validating =>
      "validating"
    case BuilderStyle.Effect =>
      "effect"
  }

  private def builderApiExpression(className: String, options: DecodedGenerateBuilder): String = options.style match {
    case BuilderStyle.Simple =>
      options.builderMethodName
    case BuilderStyle.Validating =>
      options.builderMethodName
    case BuilderStyle.Effect =>
      options.builderMethodName
  }

  private def styleSpecificBuilderMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = options.style match {
    case BuilderStyle.Simple =>
      val fieldMembers = renderSimpleFieldMembers(className, fields, options)
      s"""$fieldMembers"""
    case BuilderStyle.Validating =>
      renderValidatingBuilderMembers(className, fields, options)
    case BuilderStyle.Effect =>
      renderEffectBuilderMembers(className, fields, options)
  }

  private def primitivePolicyToExpr(value: PrimitivePolicy): String = value match {
    case PrimitivePolicy.WrappedOnly =>
      "builders.configuration.PrimitivePolicy.WrappedOnly"
    case PrimitivePolicy.PrimitiveAndWrappedIfDerivable =>
      "builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable"
    case PrimitivePolicy.PrimitiveOnly =>
      "builders.configuration.PrimitivePolicy.PrimitiveOnly"
  }

  private def pathModeToExpr(value: PathMode): String = value match {
    case PathMode.Disabled =>
      "builders.configuration.PathMode.Disabled"
    case PathMode.CustomPrefixOnly =>
      "builders.configuration.PathMode.CustomPrefixOnly"
    case PathMode.FullCollectionAware =>
      "builders.configuration.PathMode.FullCollectionAware"
  }

  private def effectModeToExpr(value: EffectMode): String = value match {
    case EffectMode.ValidationOnly =>
      "builders.configuration.EffectMode.ValidationOnly"
    case EffectMode.AbstractCapability =>
      "builders.configuration.EffectMode.AbstractCapability"
  }

  private def conversionModeToExpr(value: ConversionMode): String = value match {
    case ConversionMode.UseExistingOnly =>
      "builders.configuration.ConversionMode.UseExistingOnly"
    case ConversionMode.SynthesizeIfMissing =>
      "builders.configuration.ConversionMode.SynthesizeIfMissing"
    case ConversionMode.SynthesizeAndExposeHelpers =>
      "builders.configuration.ConversionMode.SynthesizeAndExposeHelpers"
  }

  private def staleCheckModeToExpr(value: StaleCheckMode): String = value match {
    case StaleCheckMode.SignatureHash =>
      "builders.configuration.StaleCheckMode.SignatureHash"
    case StaleCheckMode.StructuralOnly =>
      "builders.configuration.StaleCheckMode.StructuralOnly"
  }

  private def mergeModeToExpr(value: MergeMode): String = value match {
    case MergeMode.GeneratedRegionOnly =>
      "builders.configuration.MergeMode.GeneratedRegionOnly"
    case MergeMode.ReplaceGeneratedMembers =>
      "builders.configuration.MergeMode.ReplaceGeneratedMembers"
  }

  private def smartConstructorModeToExpr(value: SmartConstructorMode): String = value match {
    case SmartConstructorMode.ZValidation =>
      "builders.configuration.SmartConstructorMode.ZValidation"
    case SmartConstructorMode.Either =>
      "builders.configuration.SmartConstructorMode.Either"
    case SmartConstructorMode.Direct =>
      "builders.configuration.SmartConstructorMode.Direct"
  }

  private def errorCombinationToExpr(value: ErrorCombination): String = value match {
    case ErrorCombination.Union =>
      "builders.configuration.ErrorCombination.Union"
    case ErrorCombination.LeastUpperBound =>
      "builders.configuration.ErrorCombination.LeastUpperBound"
  }

  private def effectFailureModeToExpr(value: EffectFailureMode): String = value match {
    case EffectFailureMode.Propagate =>
      "builders.configuration.EffectFailureMode.Propagate"
    case EffectFailureMode.OrDie =>
      "builders.configuration.EffectFailureMode.OrDie"
    case EffectFailureMode.OrElseProvided =>
      "builders.configuration.EffectFailureMode.OrElseProvided"
  }

  private def generatedCodeShapeToExpr(value: GeneratedCodeShape): String = value match {
    case GeneratedCodeShape.Readable =>
      "builders.configuration.GeneratedCodeShape.Readable"
    case GeneratedCodeShape.Performance =>
      "builders.configuration.GeneratedCodeShape.Performance"
  }

  private def renderSimpleFieldMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val publicBuilderMethodName = options.builderMethodName
    if (fields.isEmpty) {
      s"""private type Builder = $className
  def $publicBuilderMethodName: Builder = $className()"""
    } else if (options.simpleOptionalValues == SimpleOptionalValues.OptionalValuesWithEmptyDefaults || options.simpleOptionalValues == SimpleOptionalValues.OptionalValuesFromDefaults) {
      renderSimpleFieldMembersWithOmittedValues(className, fields, publicBuilderMethodName, options.simpleOptionalValues)
    } else {
      val smartEnabledByField = List.fill(fields.size)(false)

      val inputAliases = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        val inputTypeExpr = renderSimpleInputTypeExpr(field, options)
        s"  private type ${capitalize(sanitized)}Input = $inputTypeExpr"
      }

      val afterStepTypeAliases = renderAfterStepTypeAliases(className, fields)
      val builderType = renderSimpleBuilderTypeExpr(className, fields)
      val conversionHelpers = renderSimpleConversionHelpers(fields, smartEnabledByField)
      val stepMethods = renderSimpleStepMethods(className, fields, smartEnabledByField)
      val firstParamName = sanitizeFieldName(fields.head.name)
      val firstParamTypeAlias = s"${capitalize(firstParamName)}Input"
      val builderImpl = s"($firstParamName= ($firstParamName: $firstParamTypeAlias) => step1($firstParamName))"

      (
        List(
          s"private type Builder = $builderType",
          s"  inline def $publicBuilderMethodName: Builder = $builderImpl"
        ) ++ inputAliases ++ afterStepTypeAliases ++ conversionHelpers ++ stepMethods
      ).mkString("\n")
    }
  }

  private def renderSimpleInputTypeExpr(field: ClassField, options: DecodedGenerateBuilder): String = {
    field.typeExpr
  }

  private def isSimpleSmartConversionEnabled(options: DecodedGenerateBuilder, field: ClassField): Boolean = {
    false
  }

  private def renderSimpleConversionHelpers(fields: List[ClassField], smartEnabledByField: List[Boolean]): List[String] = {
    Nil
  }

  private def renderSimpleStepMethods(className: String, fields: List[ClassField], smartEnabledByField: List[Boolean]): List[String] = {
    fields.indices.map { index =>
      val methodName = s"step${index + 1}"
      val params = fields.take(index + 1).map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"$sanitized: ${capitalize(sanitized)}Input"
      }.mkString(", ")
      val returnType = s"AfterStep${index + 1}"
      val body =
        if (index == fields.size - 1) {
          val args = fields.zipWithIndex.map {
            case (field, argIndex) =>
              val sanitized = sanitizeFieldName(field.name)
              if (smartEnabledByField(argIndex)) {
                s"summon[SimpleSmartConstructor[${capitalize(sanitized)}Input, ${field.typeExpr}]].fromInput($sanitized)"
              } else {
                sanitized
              }
          }.mkString(", ")
          s"$className($args)"
        } else {
          val nextField = fields(index + 1)
          val nextName = sanitizeFieldName(nextField.name)
          val previousArgs = fields.take(index + 1).map(field => sanitizeFieldName(field.name))
          val allArgs = (previousArgs :+ nextName).mkString(", ")
          s"($nextName= ($nextName: ${capitalize(nextName)}Input) => step${index + 2}($allArgs))"
        }
      s"  private inline def $methodName($params): $returnType = $body"
    }.toList
  }

  private def renderAfterStepTypeAliases(className: String, fields: List[ClassField]): List[String] = {
    val inputTypeNames = fields.map { field =>
      capitalize(sanitizeFieldName(field.name)) + "Input"
    }

    val afterTypeNames = (1 to fields.size).map(index => s"AfterStep$index")

    afterTypeNames.reverse.zipWithIndex.map {
      case (afterTypeName, reverseIndex) =>
        val stepIndex = fields.size - reverseIndex
        val rhs = if (stepIndex == fields.size) {
          className
        } else {
          val nextLabel = sanitizeFieldName(fields(stepIndex).name)
          val nextInput = inputTypeNames(stepIndex)
          val nextAfter = s"AfterStep${stepIndex + 1}"
          s"($nextLabel: $nextInput => $nextAfter)"
        }
        s"  private type $afterTypeName = $rhs"
    }.reverse.toList
  }

  private def renderSimpleBuilderTypeExpr(className: String, fields: List[ClassField]): String = {
    if (fields.isEmpty) {
      className
    } else {
      val first = fields.head
      val firstName = sanitizeFieldName(first.name)
      s"($firstName: ${capitalize(firstName)}Input => AfterStep1)"
    }
  }

  private final case class SimpleFieldPlan(
    field: ClassField,
    sanitizedName: String,
    inputTypeExpr: String,
    ctorValueFromInput: String => String,
    defaultCtorValueExpr: Option[String]
  ) {
    def omittable: Boolean = defaultCtorValueExpr.nonEmpty
  }

  private def renderSimpleFieldMembersWithOmittedValues(
    className: String,
    fields: List[ClassField],
    publicBuilderMethodName: String,
    mode: SimpleOptionalValues
  ): String = {
    val plans = fields.map(field => simpleFieldPlan(field, mode))
    val inputAliases = plans.map { plan =>
      s"  private type ${capitalize(plan.sanitizedName)}Input = ${plan.inputTypeExpr}"
    }

    val afterStepTypeAliases = (1 to plans.size).toList.map { index =>
      s"  private type AfterStep$index = ${renderSimpleOmittedStateType(index, plans, className)}"
    }

    val stateMethods = (0 to plans.size).toList.map { index =>
      renderSimpleOmittedStateMethod(index, plans, className)
    }

    (
      List(
        s"private type Builder = ${renderSimpleOmittedStateType(0, plans, className)}",
        s"  inline def $publicBuilderMethodName: Builder = state0()"
      ) ++ inputAliases ++ afterStepTypeAliases ++ stateMethods
    ).mkString("\n")
  }

  private def renderSimpleOmittedStateType(index: Int, plans: List[SimpleFieldPlan], className: String): String = {
    if (index >= plans.size) {
      className
    } else {
      val setterActions = omittedSetterTargets(index, plans).map { targetIndex =>
        val targetPlan = plans(targetIndex)
        val nextType = afterStepTypeName(targetIndex + 1, plans)
        s"${targetPlan.sanitizedName}: ${capitalize(targetPlan.sanitizedName)}Input => $nextType"
      }
      val buildAction =
        if (canBuildFrom(index, plans)) {
          List(s"build: () => ${afterStepTypeName(plans.size, plans)}")
        } else {
          Nil
        }
      (setterActions ++ buildAction).mkString("(", ", ", ")")
    }
  }

  private def renderSimpleOmittedStateMethod(index: Int, plans: List[SimpleFieldPlan], className: String): String = {
    val methodName = s"state$index"
    val stateType = afterStepTypeName(index, plans)
    val params = plans.take(index).map { plan =>
      s"${plan.sanitizedName}: ${plan.field.typeExpr}"
    }.mkString(", ")
    val signature =
      if (params.isEmpty) {
        s"  private inline def $methodName(): $stateType"
      } else {
        s"  private inline def $methodName($params): $stateType"
      }

    val body =
      if (index >= plans.size) {
        val args = plans.map(_.sanitizedName).mkString(", ")
        s"$className($args)"
      } else {
        val setterEntries = omittedSetterTargets(index, plans).map { targetIndex =>
          val targetPlan = plans(targetIndex)
          val currentArgNames = plans.take(index).map(_.sanitizedName)
          val skippedDefaults = plans.slice(index, targetIndex).map { skipped =>
            skipped.defaultCtorValueExpr.getOrElse(skipped.sanitizedName)
          }
          val selectedArg = targetPlan.ctorValueFromInput(targetPlan.sanitizedName)
          val allArgs = (currentArgNames ++ skippedDefaults :+ selectedArg).mkString(", ")
          s"${targetPlan.sanitizedName}= (${targetPlan.sanitizedName}: ${capitalize(targetPlan.sanitizedName)}Input) => state${targetIndex + 1}($allArgs)"
        }
        val buildEntry =
          if (canBuildFrom(index, plans)) {
            val currentArgNames = plans.take(index).map(_.sanitizedName)
            val defaultArgs = plans.drop(index).map { plan =>
              plan.defaultCtorValueExpr.getOrElse(plan.sanitizedName)
            }
            val args = (currentArgNames ++ defaultArgs).mkString(", ")
            List(s"build= () => state${plans.size}($args)")
          } else {
            Nil
          }
        (setterEntries ++ buildEntry).mkString("(", ", ", ")")
      }

    s"$signature = $body"
  }

  private def omittedSetterTargets(index: Int, plans: List[SimpleFieldPlan]): List[Int] = {
    if (index >= plans.size) {
      Nil
    } else {
      val targets = scala.collection.mutable.ListBuffer[Int](index)
      var probe = index + 1
      var canSkip = true
      while (probe < plans.size && canSkip) {
        canSkip = plans(probe - 1).omittable
        if (canSkip) {
          targets += probe
          probe += 1
        }
      }
      targets.toList
    }
  }

  private def canBuildFrom(index: Int, plans: List[SimpleFieldPlan]): Boolean = {
    plans.drop(index).forall(_.omittable)
  }

  private def afterStepTypeName(index: Int, plans: List[SimpleFieldPlan]): String = {
    if (index == 0) {
      "Builder"
    } else {
      s"AfterStep$index"
    }
  }

  private def simpleFieldPlan(field: ClassField, mode: SimpleOptionalValues): SimpleFieldPlan = {
    val sanitizedName = sanitizeFieldName(field.name)
    val fieldType = field.typeExpr.trim
    val normalized = fieldType.replace(" ", "")
    val optionRegex = """^(?:scala\.)?Option\[(.+)\]$""".r
    val optionalRegex = """^(?:java\.util\.)?Optional\[(.+)\]$""".r
    val optionalIntRegex = """^(?:java\.util\.)?OptionalInt$""".r
    val optionalLongRegex = """^(?:java\.util\.)?OptionalLong$""".r
    val optionalDoubleRegex = """^(?:java\.util\.)?OptionalDouble$""".r

    normalized match {
      case optionRegex(inner) =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = inner,
          ctorValueFromInput = input => s"Some($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "None")
        )
      case optionalRegex(inner) =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = inner,
          ctorValueFromInput = input => s"java.util.Optional.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.Optional.empty()")
        )
      case optionalIntRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Int",
          ctorValueFromInput = input => s"java.util.OptionalInt.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalInt.empty()")
        )
      case optionalLongRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Long",
          ctorValueFromInput = input => s"java.util.OptionalLong.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalLong.empty()")
        )
      case optionalDoubleRegex() =>
        SimpleFieldPlan(
          field = field,
          sanitizedName = sanitizedName,
          inputTypeExpr = "Double",
          ctorValueFromInput = input => s"java.util.OptionalDouble.of($input)",
          defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "java.util.OptionalDouble.empty()")
        )
      case _ =>
        nullableInnerType(fieldType) match {
          case Some(innerType) =>
            SimpleFieldPlan(
              field = field,
              sanitizedName = sanitizedName,
              inputTypeExpr = innerType,
              ctorValueFromInput = input => input,
              defaultCtorValueExpr = simpleOptionalDefault(mode, field.defaultExpr, "null")
            )
          case None =>
            SimpleFieldPlan(
              field = field,
              sanitizedName = sanitizedName,
              inputTypeExpr = field.typeExpr,
              ctorValueFromInput = input => input,
              defaultCtorValueExpr = None
            )
        }
    }
  }

  private def simpleOptionalDefault(mode: SimpleOptionalValues, declaredDefault: Option[String], emptyDefault: String): Option[String] = {
    mode match {
      case SimpleOptionalValues.OptionalValuesWithEmptyDefaults =>
        Some(emptyDefault)
      case SimpleOptionalValues.OptionalValuesFromDefaults =>
        declaredDefault
      case SimpleOptionalValues.ExplicitOptionalValues =>
        None
    }
  }

  private def nullableInnerType(rawType: String): Option[String] = {
    val parts = rawType.split("\\|").map(_.trim).filter(_.nonEmpty).toList
    if (parts.size == 2) {
      val nullAliases = Set("Null", "scala.Null")
      val nonNullParts = parts.filterNot(nullAliases.contains)
      if (nonNullParts.size == 1) {
        Some(nonNullParts.head)
      } else {
        None
      }
    } else {
      None
    }
  }

  private def renderGenericFieldMembers(
    className: String,
    fields: List[ClassField],
    startStateExpr: String,
    terminalType: String,
    buildMethodName: String
  ): String = {
    if (fields.isEmpty) {
      s"""  private val fieldSteps: List[String] = Nil
  private def $buildMethodName(): $terminalType =
    $startStateExpr.asInstanceOf[$terminalType]"""
    } else {
      val inputAliases = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"  private type ${capitalize(sanitized)}Input = ${field.typeExpr}"
      }

      val afterStepTypeAliases = renderGenericAfterStepTypeAliases(fields, terminalType)

      val stepMethodsAndNames = fields.zipWithIndex.flatMap {
        case (field, index) =>
          val sanitized = sanitizeFieldName(field.name)
          val displayName = escapeForString(field.name)
          val stepName = s"fieldStep${index + 1}${capitalize(sanitized)}"
          val inputTypeAlias = s"${capitalize(sanitized)}Input"
          val currentStateType = if (index == 0) "Builder" else s"AfterStep$index"
          val nextStateType = s"AfterStep${index + 1}"
          List(
            s"  private def $stepName(current: $currentStateType, input: $inputTypeAlias): $nextStateType = {",
            s"    current.`$displayName`(input)",
            "  }",
            s"  private val ${sanitized}StepName: String = \"$displayName\""
          )
      }

      val stepList = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"${sanitized}StepName"
      }.mkString(", ")

      val parameterDecl = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"${sanitized}Value: ${capitalize(sanitized)}Input"
      }.mkString(", ")

      val stateLines = fields.zipWithIndex.map {
        case (field, index) =>
          val sanitized = sanitizeFieldName(field.name)
          val stepName = s"fieldStep${index + 1}${capitalize(sanitized)}"
          val previous = if (index == 0) startStateExpr else s"afterStep$index"
          val current = s"afterStep${index + 1}"
          s"    val $current: AfterStep${index + 1} = $stepName($previous, ${sanitized}Value)"
      }

      val buildHelper = (
        List(
          s"  private val fieldSteps: List[String] = List($stepList)",
          s"  private def $buildMethodName($parameterDecl): $terminalType = {"
        ) ++ stateLines ++ List(
          s"    afterStep${fields.size}",
          "  }"
        )
      ).mkString("\n")

      (inputAliases ++ afterStepTypeAliases ++ stepMethodsAndNames :+ buildHelper).mkString("\n")
    }
  }

  private def renderGenericAfterStepTypeAliases(
    fields: List[ClassField],
    terminalType: String
  ): List[String] = {
    val inputTypeNames = fields.map { field =>
      capitalize(sanitizeFieldName(field.name)) + "Input"
    }

    val afterTypeNames = (1 to fields.size).map(index => s"AfterStep$index")

    afterTypeNames.reverse.zipWithIndex.map {
      case (afterTypeName, reverseIndex) =>
        val stepIndex = fields.size - reverseIndex
        val rhs = if (stepIndex == fields.size) {
          terminalType
        } else {
          val nextLabel = sanitizeFieldName(fields(stepIndex).name)
          val nextInput = inputTypeNames(stepIndex)
          val nextAfter = s"AfterStep${stepIndex + 1}"
          s"($nextLabel: $nextInput => $nextAfter)"
        }
        s"  private type $afterTypeName = $rhs"
    }.reverse.toList
  }

  private def renderBuilderInputTuple(fields: List[ClassField]): String = {
    fields.map { field =>
      val sanitized = sanitizeFieldName(field.name)
      s"$sanitized: ${field.typeExpr}"
    }.mkString(", ")
  }

  private def sanitizeFieldName(value: String): String = {
    val cleaned = value.replaceAll("[^A-Za-z0-9_]", "")
    val base = if (cleaned.isEmpty) "field" else cleaned
    if (base.headOption.exists(_.isDigit)) {
      "field" + base
    } else {
      base
    }
  }

  private def capitalize(value: String): String = {
    if (value.isEmpty) {
      value
    } else {
      value.substring(0, 1).toUpperCase + value.substring(1)
    }
  }

  private def escapeForString(value: String): String = {
    value.replace("\\", "\\\\").replace("\"", "\\\"")
  }

  private def renderValidatingBuilderMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val extraVariantNames =
      if (options.generateExtraVariants) {
        List(options.builderMethodName + "Allow", options.builderMethodName + "NoAllow")
      } else {
        Nil
      }
    renderLocalValidatedBuilderMembers(
      className,
      fields,
      options,
      buildMethodName = "buildValidationFromValues",
      extraVariantNames = extraVariantNames,
      isEffect = false
    )
  }

  private def renderEffectBuilderMembers(className: String, fields: List[ClassField], options: DecodedGenerateBuilder): String = {
    val extraVariantNames =
      if (options.generateExtraVariants) {
        List(options.builderMethodName + "Effect")
      } else {
        Nil
      }
    renderLocalValidatedBuilderMembers(
      className,
      fields,
      options,
      buildMethodName = "buildEffectFromValues",
      extraVariantNames = extraVariantNames,
      isEffect = true
    )
  }

  private def renderLocalValidatedBuilderMembers(
    className: String,
    fields: List[ClassField],
    options: DecodedGenerateBuilder,
    buildMethodName: String,
    extraVariantNames: List[String],
    isEffect: Boolean
  ): String = {
    val combinedErrorTypeExpr = renderCombinedErrorTypeExpr(fields, options.combineErrors)
    val terminalType =
      if (isEffect && options.effectFailureMode != EffectFailureMode.Propagate) {
        s"zio.ZIO[Any, Nothing, $className]"
      } else {
        s"zio.prelude.ZValidation[Nothing, $combinedErrorTypeExpr, $className]"
      }
    val publicBuilderMethodName = options.builderMethodName
    val requiresFallback = isEffect && options.effectFailureMode == EffectFailureMode.OrElseProvided
    val publicMethodSignature =
      if (requiresFallback) {
        s"def $publicBuilderMethodName(fallback: => zio.ZIO[Any, Nothing, $className]): Builder = builderState0(fallback)"
      } else {
        s"def $publicBuilderMethodName: Builder = builderState0()"
      }
    val builderTypeDef =
      if (fields.isEmpty) {
        s"  type Builder = $terminalType"
      } else {
        val first = fields.head
        val firstName = sanitizeFieldName(first.name)
        val firstInput = s"${capitalize(firstName)}Input"
        s"  type Builder = ($firstName: $firstInput => AfterStep1)"
      }
    val publicBuilderDefs =
      (List(s"  $publicMethodSignature") ++
        extraVariantNames.map { variantName =>
          if (requiresFallback) {
            s"  def $variantName(fallback: => zio.ZIO[Any, Nothing, $className]): Builder = builderState0(fallback)"
          } else {
            s"  def $variantName: Builder = builderState0()"
          }
        })
        .mkString("\n")
    val fieldMembers = renderLocalValidatedFieldMembers(
      className,
      fields,
      terminalType,
      buildMethodName,
      combinedErrorTypeExpr,
      options.generatedCodeShape,
      isEffect,
      options.effectFailureMode,
      requiresFallback
    )
s"""$builderTypeDef
$publicBuilderDefs
$fieldMembers"""
  }

  private def renderLocalValidatedFieldMembers(
    className: String,
    fields: List[ClassField],
    terminalType: String,
    buildMethodName: String,
    combinedErrorTypeExpr: String,
    generatedCodeShape: GeneratedCodeShape,
    isEffect: Boolean,
    effectFailureMode: EffectFailureMode,
    requiresFallback: Boolean
  ): String = {
    val inputAliases = fields.map { field =>
      val sanitized = sanitizeFieldName(field.name)
      s"  private type ${capitalize(sanitized)}Input = ${renderValidatedInputTypeExpr(field)}"
    }
    val afterStepTypeAliases = renderGenericAfterStepTypeAliases(fields, terminalType)
    val validationHelpers = renderValidationHelpers(fields, generatedCodeShape)
    val stateMethods = renderSelectableStateMethods(className, fields, buildMethodName, requiresFallback)
    val buildHelper = renderLocalValidationBuildHelper(
      className,
      fields,
      terminalType,
      buildMethodName,
      combinedErrorTypeExpr,
      generatedCodeShape,
      isEffect,
      effectFailureMode,
      requiresFallback
    )

    (inputAliases ++ afterStepTypeAliases ++ validationHelpers ++ stateMethods :+ buildHelper).mkString("\n")
  }

  private def renderValidatedInputTypeExpr(field: ClassField): String = {
    field.smartCtorInputTypeExpr.getOrElse(field.typeExpr)
  }

  private def renderValidationHelpers(fields: List[ClassField], generatedCodeShape: GeneratedCodeShape): List[String] = {
    fields.map { field =>
      val sanitized = sanitizeFieldName(field.name)
      val capitalized = capitalize(sanitized)
      val helperExpr = renderValidationHelperExpr(field, sanitized, capitalized, generatedCodeShape)
      val validationErrorTypeExpr = renderFieldErrorTypeExpr(field)
      val givenDef =
        if (generatedCodeShape == GeneratedCodeShape.Performance) {
          s"""  private inline given ${sanitized}SmartConstructor: (${capitalized}Input => ${capitalized}Validation) =
    (${sanitized}Value: ${capitalized}Input) => $helperExpr"""
        } else {
          s"""  private given ${sanitized}SmartConstructor: (${capitalized}Input => ${capitalized}Validation) =
    new ((${capitalized}Input => ${capitalized}Validation)) {
      def apply(${sanitized}Value: ${capitalized}Input): ${capitalized}Validation = $helperExpr
    }"""
        }
      s"""  private type ${capitalized}Validation = zio.prelude.ZValidation[Nothing, $validationErrorTypeExpr, ${field.typeExpr}]
$givenDef
  private inline def validate$capitalized(${sanitized}Value: ${capitalized}Input): ${capitalized}Validation =
    summon[${capitalized}Input => ${capitalized}Validation].apply(${sanitized}Value)"""
    }
  }

  private def renderValidationHelperExpr(
    field: ClassField,
    sanitized: String,
    capitalized: String,
    generatedCodeShape: GeneratedCodeShape
  ): String = {
    val inputValue = s"${sanitized}Value"
    (field.smartCtorMethodName, field.smartCtorResultKind) match {
      case (Some(methodName), Some(resultKind)) =>
        val invocation = renderSmartConstructorInvocation(field.typeExpr, methodName, inputValue)
        resultKind match {
          case SmartCtorResultKind.Validation =>
            if (generatedCodeShape == GeneratedCodeShape.Performance) {
              s"$invocation.asInstanceOf[${capitalized}Validation]"
            } else {
              s"$invocation.mapError(error => error: ${renderFieldErrorTypeExpr(field)})"
            }
          case SmartCtorResultKind.EitherResult =>
            if (generatedCodeShape == GeneratedCodeShape.Performance) {
              s"zio.prelude.ZValidation.fromEither($invocation).asInstanceOf[${capitalized}Validation]"
            } else {
              s"zio.prelude.ZValidation.fromEither($invocation).mapError(error => error: ${renderFieldErrorTypeExpr(field)})"
            }
          case SmartCtorResultKind.Direct =>
            if (generatedCodeShape == GeneratedCodeShape.Performance) {
              s"zio.prelude.ZValidation.succeed($invocation).asInstanceOf[${capitalized}Validation]"
            } else {
              s"zio.prelude.ZValidation.succeed($invocation)"
            }
        }
      case _ =>
        if (generatedCodeShape == GeneratedCodeShape.Performance) {
          s"zio.prelude.ZValidation.succeed($inputValue).asInstanceOf[${capitalized}Validation]"
        } else {
          s"zio.prelude.ZValidation.succeed($inputValue)"
        }
    }
  }

  private def renderSmartConstructorInvocation(typeExpr: String, methodName: String, inputValue: String): String = {
    val companionExpr = smartConstructorCompanionExpr(typeExpr)
    methodName match {
      case "apply" =>
        s"$companionExpr($inputValue)"
      case other =>
        s"$companionExpr.$other($inputValue)"
    }
  }

  private def smartConstructorCompanionExpr(typeExpr: String): String = {
    val trimmed = typeExpr.trim
    if (trimmed.endsWith(".Type")) {
      trimmed.stripSuffix(".Type")
    } else {
      trimmed
    }
  }

  private def renderSelectableStateMethods(
    className: String,
    fields: List[ClassField],
    buildMethodName: String,
    requiresFallback: Boolean
  ): List[String] = {
    if (fields.isEmpty) {
      val fallbackParam =
        if (requiresFallback) {
          s"fallback: => zio.ZIO[Any, Nothing, $className]"
        } else {
          ""
        }
      val fallbackArg = if (requiresFallback) "fallback" else ""
      val paramSection = if (fallbackParam.isEmpty) "" else fallbackParam
      val callArgs = if (fallbackArg.isEmpty) "" else fallbackArg
      List(s"  private inline def builderState0($paramSection): Builder = $buildMethodName($callArgs)")
    } else {
      val builderStates = (0 until fields.size).map { index =>
        val methodName = s"builderState$index"
        val valueParams = fields.take(index).map { field =>
          val sanitized = sanitizeFieldName(field.name)
          s"${sanitized}Value: ${capitalize(sanitized)}Input"
        }
        val fallbackParams =
          if (requiresFallback) {
            List(s"fallback: => zio.ZIO[Any, Nothing, $className]")
          } else {
            Nil
          }
        val params = (fallbackParams ++ valueParams).mkString(", ")
        val returnType = if (index == 0) "Builder" else s"AfterStep$index"
        val currentField = fields(index)
        val currentName = sanitizeFieldName(currentField.name)
        val currentInputType = s"${capitalize(currentName)}Input"
        val nextArgValues = fields.take(index).map(field => sanitizeFieldName(field.name) + "Value") :+ s"${currentName}Value"
        val nextArgs =
          if (requiresFallback) {
            (List("fallback") ++ nextArgValues).mkString(", ")
          } else {
            nextArgValues.mkString(", ")
          }
        val nextExpr =
          if (index == fields.size - 1) {
            s"$buildMethodName($nextArgs)"
          } else {
            s"builderState${index + 1}($nextArgs)"
          }
        val paramSection = if (params.isEmpty) "" else params
        s"""  private inline def $methodName($paramSection): $returnType =
    ($currentName = (${currentName}Value: $currentInputType) => $nextExpr)"""
      }
      val terminalState = {
        val valueParams = fields.map { field =>
          val sanitized = sanitizeFieldName(field.name)
          s"${sanitized}Value: ${capitalize(sanitized)}Input"
        }
        val fallbackParams =
          if (requiresFallback) {
            List(s"fallback: => zio.ZIO[Any, Nothing, $className]")
          } else {
            Nil
          }
        val params = (fallbackParams ++ valueParams).mkString(", ")
        val valueArgs = fields.map(field => sanitizeFieldName(field.name) + "Value")
        val callArgs =
          if (requiresFallback) {
            (List("fallback") ++ valueArgs).mkString(", ")
          } else {
            valueArgs.mkString(", ")
          }
        s"  private inline def builderState${fields.size}($params): AfterStep${fields.size} = $buildMethodName($callArgs)"
      }
      (builderStates :+ terminalState).toList
    }
  }

  private def renderLocalValidationBuildHelper(
    className: String,
    fields: List[ClassField],
    terminalType: String,
    buildMethodName: String,
    combinedErrorTypeExpr: String,
    generatedCodeShape: GeneratedCodeShape,
    isEffect: Boolean,
    effectFailureMode: EffectFailureMode,
    requiresFallback: Boolean
  ): String = {
    val fallbackParamDecl =
      if (requiresFallback) {
        s", fallback: => zio.ZIO[Any, Nothing, $className]"
      } else {
        ""
      }

    def finalizeEffect(validationExpr: String): String = {
      if (!isEffect || effectFailureMode == EffectFailureMode.Propagate) {
        validationExpr
      } else if (effectFailureMode == EffectFailureMode.OrDie) {
        s"$validationExpr.toEither match { case Right(value) => zio.ZIO.succeed(value); case Left(errors) => zio.ZIO.dieMessage(errors.toString) }"
      } else {
        s"$validationExpr.toEither match { case Right(value) => zio.ZIO.succeed(value); case Left(_) => fallback }"
      }
    }

    if (fields.isEmpty) {
      val validationExpr =
        if (generatedCodeShape == GeneratedCodeShape.Performance) {
          s"zio.prelude.ZValidation.succeed($className()).asInstanceOf[zio.prelude.ZValidation[Nothing, $combinedErrorTypeExpr, $className]]"
        } else {
          s"zio.prelude.ZValidation.succeed($className())"
        }
      val finalExpr = finalizeEffect(validationExpr)
      s"""  private def $buildMethodName(${
        if (requiresFallback) {
          s"fallback: => zio.ZIO[Any, Nothing, $className]"
        } else {
          ""
        }
      }): $terminalType =
    $finalExpr"""
    } else if (fields.size == 1) {
      val field = fields.head
      val sanitized = sanitizeFieldName(field.name)
      val capitalized = capitalize(sanitized)
      val fieldErrorTypeExpr = renderFieldErrorTypeExpr(field)
      val readableValidationExpr =
        if (fieldErrorTypeExpr == "Nothing" || fieldErrorTypeExpr == combinedErrorTypeExpr) {
          s"validate$capitalized(${sanitized}Value)"
        } else {
          s"validate$capitalized(${sanitized}Value).mapError(error => error: $combinedErrorTypeExpr)"
        }
      val validationExpr =
        if (generatedCodeShape == GeneratedCodeShape.Performance) {
          s"validate$capitalized(${sanitized}Value).asInstanceOf[zio.prelude.ZValidation[Nothing, $combinedErrorTypeExpr, ${field.typeExpr}]].map(${sanitized}Validated => $className(${sanitized}Validated))"
        } else {
          s"$readableValidationExpr.map(${sanitized}Validated => $className(${sanitized}Validated))"
        }
      val finalExpr = finalizeEffect(validationExpr)
      s"""  private def $buildMethodName(${sanitized}Value: ${capitalized}Input$fallbackParamDecl): $terminalType =
    $finalExpr"""
    } else {
      val parameterDecl = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        s"${sanitized}Value: ${capitalize(sanitized)}Input"
      }.mkString(", ")
      val validationCalls = fields.map { field =>
        val sanitized = sanitizeFieldName(field.name)
        val capitalized = capitalize(sanitized)
        val fieldErrorTypeExpr = renderFieldErrorTypeExpr(field)
        if (generatedCodeShape == GeneratedCodeShape.Performance) {
          s"      validate$capitalized(${sanitized}Value).asInstanceOf[zio.prelude.ZValidation[Nothing, $combinedErrorTypeExpr, ${field.typeExpr}]]"
        } else {
          if (fieldErrorTypeExpr == "Nothing" || fieldErrorTypeExpr == combinedErrorTypeExpr) {
            s"      validate$capitalized(${sanitized}Value)"
          } else {
            s"      validate$capitalized(${sanitized}Value).mapError(error => error: $combinedErrorTypeExpr)"
          }
        }
      }.mkString(",\n")
      val validatedParams = fields.map(field => sanitizeFieldName(field.name) + "Validated").mkString(", ")
      val validationExpr = s"zio.prelude.Validation.validateWith(\n$validationCalls\n    )(($validatedParams) => $className($validatedParams))"
      val finalExpr = finalizeEffect(validationExpr)
      s"""  private def $buildMethodName($parameterDecl$fallbackParamDecl): $terminalType =
    $finalExpr"""
    }
  }

  private def renderFieldErrorTypeExpr(field: ClassField): String = {
    field.smartCtorResultKind match {
      case Some(SmartCtorResultKind.Direct) =>
        "Nothing"
      case Some(SmartCtorResultKind.Validation) | Some(SmartCtorResultKind.EitherResult) =>
        "Any"
      case None =>
        "Nothing"
    }
  }

  private def renderCombinedErrorTypeExpr(fields: List[ClassField], combineErrors: ErrorCombination): String = {
    val fieldErrorTypes = fields.map(renderFieldErrorTypeExpr)
    combineErrors match {
      case ErrorCombination.LeastUpperBound =>
        if (fieldErrorTypes.forall(_ == "Nothing")) "Nothing" else "Any"
      case ErrorCombination.Union =>
        val nonNothing = fieldErrorTypes.filterNot(_ == "Nothing").distinct
        if (nonNothing.isEmpty) {
          "Nothing"
        } else {
          nonNothing.mkString(" | ")
        }
    }
  }

}
