import builders.configuration.*

@GenerateBuilder(
  style = BuilderStyle.Effect,
  primitivePolicy = PrimitivePolicy.WrappedOnly,
  pathMode = PathMode.CustomPrefixOnly,
  effectMode = EffectMode.AbstractCapability,
  conversionMode = ConversionMode.SynthesizeAndExposeHelpers,
  staleCheckMode = StaleCheckMode.StructuralOnly,
  mergeMode = MergeMode.ReplaceGeneratedMembers
)
case class EffectGoldenUser(id: Int)

object EffectGoldenUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Effect
  private val modeTag: String = "effect"
  private val builderApi: Any = builder
    type Builder = (id: IdInput => AfterStep1)
  def builder: Builder = builderState0()
  def builderEffect: Builder = builderState0()
  private type IdInput = Int
  private type AfterStep1 = zio.prelude.ZValidation[Nothing, Nothing, EffectGoldenUser]
  private type IdValidation = zio.prelude.ZValidation[Nothing, Nothing, Int]
  private inline given idSmartConstructor: (IdInput => IdValidation) =
    (idValue: IdInput) => zio.prelude.ZValidation.succeed(idValue).asInstanceOf[IdValidation]
  private inline def validateId(idValue: IdInput): IdValidation =
    summon[IdInput => IdValidation].apply(idValue)
  private inline def builderState0(): Builder =
    (id = (idValue: IdInput) => buildEffectFromValues(idValue))
  private inline def builderState1(idValue: IdInput): AfterStep1 = buildEffectFromValues(idValue)
  private def buildEffectFromValues(idValue: IdInput): zio.prelude.ZValidation[Nothing, Nothing, EffectGoldenUser] =
    validateId(idValue).asInstanceOf[zio.prelude.ZValidation[Nothing, Nothing, Int]].map(idValidated => EffectGoldenUser(idValidated))
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.WrappedOnly
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.CustomPrefixOnly
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.AbstractCapability
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeAndExposeHelpers
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.StructuralOnly
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.ReplaceGeneratedMembers
  private val smartConstructorMode: builders.configuration.SmartConstructorMode = builders.configuration.SmartConstructorMode.ZValidation
  private val combineErrors: builders.configuration.ErrorCombination = builders.configuration.ErrorCombination.Union
  private val effectFailureMode: builders.configuration.EffectFailureMode = builders.configuration.EffectFailureMode.Propagate
  // format: on
}