import builders.configuration.*

@GenerateBuilder(
  style = BuilderStyle.Effect,
  primitivePolicy = PrimitivePolicy.WrappedOnly,
  pathMode = PathMode.CustomPrefixOnly,
  effectMode = EffectMode.AbstractCapability,
  conversionMode = ConversionMode.SynthesizeAndExposeHelpers,
  staleCheckMode = StaleCheckMode.StructuralOnly,
  mergeMode = MergeMode.ReplaceGeneratedMembers
)
case class EffectGoldenUser(id: Int)

object EffectGoldenUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Effect
  private val modeTag: String = "effect"
  private val builderApi: Any = api.ValidatedBuilderGenerator.builder[EffectGoldenUser]
  private type Builder = api.ValidatedBuilderSelectable[EffectGoldenUser, ?, (id: Int)]
  def builder: Builder = api.ValidatedBuilderGenerator.builder[EffectGoldenUser]
  def builderEffect: Builder = builder
  private def derived: api.ValidatedBuilderGenerator[EffectGoldenUser] = api.ValidatedBuilderGenerator.derived[EffectGoldenUser]
  private def builderRef: Builder = builder
  // Effect backend is currently modeled through the validated builder seam.
  private def builderEffectRef: Any = builderEffect
  private type IdInput = Int
  private type AfterStep1 = zio.prelude.ZValidation[Nothing, ?, EffectGoldenUser]
  private def fieldStep1Id(current: Builder, input: IdInput): AfterStep1 = {
    current.`id`(input)
  }
  private val idStepName: String = "id"
  private val fieldSteps: List[String] = List(idStepName)
  private def buildEffectFromValues(idValue: IdInput): zio.prelude.ZValidation[Nothing, ?, EffectGoldenUser] = {
    val afterStep1: AfterStep1 = fieldStep1Id(builderEffect, idValue)
    afterStep1
  }
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.WrappedOnly
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.CustomPrefixOnly
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.AbstractCapability
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeAndExposeHelpers
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.StructuralOnly
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.ReplaceGeneratedMembers
  // format: on
}
