package models

import api.ValidatedBuilderGenerator
import playground.Opaque

/**
 * A simple test case class that uses types with validation.
 */
case class SimpleValidated(
  i: Int,
  op: Opaque.Op
)

object SimpleValidated {
  // The builder will be generated by the macro
  val validator: ValidatedBuilderGenerator[SimpleValidated] = ValidatedBuilderGenerator.derived[SimpleValidated]
}
