package models

import api.ValidatedBuilderGenerator
import playground.Opaque

import java.time.LocalDate

/**
 * A simple test case class that uses types with validation.
 */
case class SimpleValidated(
                            i: Int,
                            op: Opaque.Op
                          )

object SimpleValidated {
  import Opaque.Op
  // The builder will be generated by the macro; expose the NamedTuple builder directly
  // For primitively-typed builders with validation, we need to use reflective selection
  val validator: Any = ValidatedBuilderGenerator.builder[SimpleValidated]//.asInstanceOf[Selectable]
}


final case class Simple(i: Int, s: String, d: LocalDate)

object Simple {
  val validator: ValidatedBuilderGenerator[Simple] = ValidatedBuilderGenerator.derived[Simple]
}