package models

import api.ValidatedBuilderGenerator
import playground.Opaque

import java.time.LocalDate

/**
 * A simple test case class that uses types with validation.
 */
case class SimpleValidated(
                            i: Int,
                            op: Opaque.Op
                          )

object SimpleValidated {
  // The builder will be generated by the macro
  val validator: ValidatedBuilderGenerator[SimpleValidated] = ValidatedBuilderGenerator.derived[SimpleValidated]
}


final case class Simple(i: Int, s: String, d: LocalDate)

object Simple {
  val validator: ValidatedBuilderGenerator[Simple] = ValidatedBuilderGenerator.derived[Simple]
}