package testkit.simple



import scala.annotation.StaticAnnotation

object BuilderStyle {
  val Simple: String = "Simple"
}

final class GenerateBuilder(
  val style: String = "Simple",
  val builderMethodName: String = "builder",
  val generateExtraVariants: Boolean = true
) extends StaticAnnotation

@GenerateBuilder(style = BuilderStyle.Simple)
case class SimpleUser(id: Int, name: String)

object SimpleUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Simple
  private val modeTag: String = "simple"
  private val builderApi: Any = builder
  private type Builder = (id: IdInput => AfterStep1)
  inline def builder: Builder = (id= (id: IdInput) => step1(id))
  private type IdInput = Int
  private type NameInput = String
  private type AfterStep1 = (name: NameInput => AfterStep2)
  private type AfterStep2 = SimpleUser
  private inline def step1(id: IdInput): AfterStep1 = (name= (name: NameInput) => step2(id, name))
  private inline def step2(id: IdInput, name: NameInput): AfterStep2 = SimpleUser(id, name)
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}
