package testkit.validating



import scala.annotation.StaticAnnotation

object BuilderStyle {
  val Validating: String = "Validating"
}

final class GenerateBuilder(
  val style: String = "Validating",
  val builderMethodName: String = "builder",
  val generateExtraVariants: Boolean = true
) extends StaticAnnotation

@GenerateBuilder(style = BuilderStyle.Validating, builderMethodName = "make", generateExtraVariants = false)
case class NamedUser(id: Int, code: String)

object NamedUser {
  // format: off
  // generated by GenerateBuildersRule
  private val generatorRuleVersion: String = "0.1.0-SNAPSHOT"
  private val style: builders.configuration.BuilderStyle = builders.configuration.BuilderStyle.Validating
  private val modeTag: String = "validating"
  private val builderApi: Any = api.ValidatedBuilderGenerator.builder[NamedUser]
  private type Builder = api.ValidatedBuilderSelectable[NamedUser, ?, (id: Int, code: String)]
  def make: Builder = api.ValidatedBuilderGenerator.builder[NamedUser]

  private def derived: api.ValidatedBuilderGenerator[NamedUser] = api.ValidatedBuilderGenerator.derived[NamedUser]
  private def derivedAllow: api.ValidatedBuilderGenerator[NamedUser] = api.ValidatedBuilderGenerator.derivedAllow[NamedUser]
  private def derivedNoAllow: api.ValidatedBuilderGenerator[NamedUser] = api.ValidatedBuilderGenerator.derivedNoAllow[NamedUser]
  private def builderRef: Builder = make

  private type IdInput = Int
  private type CodeInput = String
  private type AfterStep1 = api.ValidatedBuilderSelectable[NamedUser, ?, (code: CodeInput)]
  private type AfterStep2 = zio.prelude.ZValidation[Nothing, ?, NamedUser]
  private def fieldStep1Id(current: Builder, input: IdInput): AfterStep1 = {
    current.`id`(input)
  }
  private val idStepName: String = "id"
  private def fieldStep2Code(current: AfterStep1, input: CodeInput): AfterStep2 = {
    current.`code`(input)
  }
  private val codeStepName: String = "code"
  private val fieldSteps: List[String] = List(idStepName, codeStepName)
  private def buildValidationFromValues(idValue: IdInput, codeValue: CodeInput): zio.prelude.ZValidation[Nothing, ?, NamedUser] = {
    val afterStep1: AfterStep1 = fieldStep1Id(make, idValue)
    val afterStep2: AfterStep2 = fieldStep2Code(afterStep1, codeValue)
    afterStep2
  }
  private val primitivePolicy: builders.configuration.PrimitivePolicy = builders.configuration.PrimitivePolicy.PrimitiveAndWrappedIfDerivable
  private val pathMode: builders.configuration.PathMode = builders.configuration.PathMode.FullCollectionAware
  private val effectMode: builders.configuration.EffectMode = builders.configuration.EffectMode.ValidationOnly
  private val conversionMode: builders.configuration.ConversionMode = builders.configuration.ConversionMode.SynthesizeIfMissing
  private val staleCheckMode: builders.configuration.StaleCheckMode = builders.configuration.StaleCheckMode.SignatureHash
  private val mergeMode: builders.configuration.MergeMode = builders.configuration.MergeMode.GeneratedRegionOnly
  // format: on
}
